#!/usr/bin/env node
/* A builder, not a check: the text fixes, and the people of Land King Hall
   as another cast, each line of theirs rewritten and their names changed
   (24 September 2026, at the maintainer's word; a variant for fun).

   Usage: node utilities/rickmorty_patch.mjs index.html "<Cythera Data.data>" <out dir>

   Alaric is Rick, the scientist; Magpie is Morgie, who speaks as Morty;
   Omen is Mr. Creepsneaks, a Meeseeks; the Test's scrolls are written by
   a Mr. Poopybutthole; Hector is Hekker, who speaks as Summer; Hadrian is
   Harry, who speaks as Jerry; Emesa is Bethesa, who speaks as Beth; the
   hall's guard is Krombopulos Michael, who just loves killing. The lines
   are the shared table in hall_lines.mjs, the machinery castEdits there:
   click marks and highlighted words kept, the names changed in the name
   table, in every mention and in the keyword lists ("morg", "hekk",
   "harr", "beth" join "magp", "hect", "hadr", "emes"; "rick" joins
   "alar"). A burp is written "(burp)": an asterisk in a line is the
   game's click mark. */
import {fileURLToPath} from 'node:url';
import {buildCast} from './hall_lines.mjs';

export const CAST = {
  name: 'Cythera Voices of the Hall (Rick and Morgie)',
  description: 'The text fixes, and the people of Land King Hall as Rick, Morgie, Mr. Creepsneaks, Hekker, Harry, Bethesa and Krombopulos Michael, with the Test’s scrolls by a Mr. Poopybutthole.',
  names: { Alaric: 'Rick', Magpie: 'Morgie', Hadrian: 'Harry', Emesa: 'Bethesa', Hector: 'Hekker', 'LKH Guard': 'Krombopulos Michael', Omen: 'Mr. Creepsneaks' },
  omenResids: [0x0242, 0x10EA, 0x1428, 0x1801, 0x1CC3],
  keywords: [['alar', 'rick'], ['magp', 'morg'], ['hadr', 'harr'], ['emes', 'beth'], ['hect', 'hekk']],
  lines: {
    // ---- Rick ---------------------------------------------------------
    rick_description: `Before you stands an older man in a lab coat, with wild hair, a unibrow, and something green drying on his chin`,
    rick_desperate: `, but with a look of desperation, and a flask.`,
    rick_satisfied: `, with a look of satisfaction, and a flask.`,
    rick_relieved: `, with a look of relief, calm, and a flask.`,
    rick_the_dark_ending: `Just before your vision fades completely, the face of Rick wavers.*`,
    rick_possessed: `"Yes, thank you, foolish mortal - without you, we never would have gained control of he who was once Rick."*"With the powers of the Crolna, Land King Hall and all humanity behind us, we shall make short work of the Seldane."*"And then we can rid ourselves of the humans as well - our victory has been sealed.  (burp)  Huh.  Some of him is still in here."*`,
    rick_piemag_vision: `Just before it fades completely, the vision of Morgie appears before you.`,
    rick_bahoudin_thanks: `*"Aw geez, uh, B-Bahoudin says thanks for curing Rick.  If Rick's mom, Chrysothemis, was alive today, she'd, y'know, thank you too, I guess."*"But she's not, so.  Still, her husband, Rick's dad, Bahoudin, says thanks for saving his son.  Oh man, this is a lot of family stuff."*`,
    rick_first_speech: `"Oh, good, you're up.  (burp)  Great.  We were, like, medium worried you were dead."*"Okay, so, I should probably explain the situation, since you've got that look.  My name is Rick and you are now in the land of @Cythera.  It's a dimension.  You're in a dimension, don't freak out."*"You were summoned in a final, desperate, frankly kind of pathetic attempt to save Cythera and its ruler from chaos and madness.  Spoiler: the ruler's me."*"I'm that ruler, and I've got a special @bond with the land and the people of Cythera.  It's science, it's not magic, everybody calls it magic, whatever.  For over two hundred years I've kept this place prosperous, and nobody's said thank you once."*"Unfortunately, the last couple of years my power's been draining, and with it, Cythera's been slipping into chaos.  It's a whole thing."*"It's like the bond is dissolving, the land's changing somehow. And I don't understand it, which, for me, is - (burp) - that's new.  I don't like new."*"The more impotent I get, the more it drives me nuts watching it slip away, like waking up from a dream you were actually good at..."*"So I trusted the fates - the fates, me, I know - to summon an outsider, from @Mater Theia herself, because only an outsider can see through this cloud that's blocking my vision.  That's not a metaphor, there's an actual cloud."*"You, obviously, are that outsider.  Don't think I did this on a whim - it cost me most of my remaining power, which is a lot of power, you have no idea."*"So I've got to trust you to help me.  Sorry about the danger.  Not that sorry.  You're my, and Cythera's, last chance, so, y'know, don't be a Jerry about it."`,
    rick_rude_of_me: `"I'm Rick - did I tell you already?  I don't repeat myself.  Except that time.  (burp)\n"`,
    rick_keeper: `"I'm the keeper of the land of Cythera,`,
    rick_thanks_to_you: ` thanks to you, apparently.  Don't let it go to your head."`,
    rick_stranger: ` and some days I feel like I'm in the wrong dimension.  Which, statistically, I probably am."`,
    rick_look_you_over: `"Okay, hold still, let me scan you..."*`,
    rick_that_should_help: `"There.  That should help.  I'm a genius, you're welcome."`,
    rick_good_shape: `"You're fine.  You're in, like, aggressively adequate shape."`,
    rick_stained: `"Yeah, no.  Your soul's got too much crap on it for me to clean, and I've cleaned some souls."`,
    rick_register: `"Can't help you till you've registered this software.  I don't make the rules.  I mean, I could, but I didn't."`,
    rick_no_experience: `"You don't have enough experience for more training.  Go do stuff.  Come back.  Repeat."`,
    rick_amulet: `"Here, take this amulet - it's got my symbol on it.  Wear it around your neck and it'll save your life if you die.  Once.  Well, a few times.  I didn't count."*"You can also use it to bring a friend back from the halls of death, but heads up, it has a limited number of charges, and no, I'm not making you another one."*He tosses you an amulet on a gold chain without looking.*`,
    rick_quarters: `*"I've got some quarters set up for you - Morgie will show you around.  Morgie!  Morgie, get in here."*`,
    piemag_follow: `"Aw geez, okay, uh, f-follow me, I guess."*`,
    piemag_the_library: `Morgie points to the end of the hall to the north.*"So, uh, at the end of the hall there's the Library."*"There's a lot of, y'know, learning in there, from books the elders wrote.  Rick says it's mostly wrong but you should probably read it anyway."*`,
    piemag_the_quarters: `"S-so these are your quarters.  There's provisions in there.  Rick says don't eat the green stuff."*"The things in your quarters are yours, so, y'know, use them."*"But, uh, don't steal from other people, okay?  Cythera's an honorable land and stealing gets you in real trouble.  I-I've seen it."*Morgie looks around nervously.*"Look, I'm just the fool, okay, but even I know your journey's gonna be dangerous.  Like, really dangerous.  Oh man."*"You should learn what you can.  Important people come and go around here, but you're, like, unique, apparently.  Rick said so."*"Demodocus is staying across the hall for now.  I'd talk to him if I were you.  Actually, if I were you I'd go home, but you can't, so."*"Also, uh, maybe ask around and see if somebody wants to @join you on your quest...  Please don't ask me."`,
    rick_help_me: `"Please.  Do what you can to help me.  I said please.  That's - (burp) - that's basically unprecedented."`,
    rick_odemia: `"Odemia's the closest city - go east, follow the coast, don't die."`,
    rick_the_land: `"Yes, Cythera is the land.  It's a land.  Great question."`,
    rick_one_again: `"I'm one with the land again, thanks to you.  Wubba lubba dub dub."`,
    rick_the_bond: `"I am, or was, one with the land and its people.  I provided all their basic needs - a bountiful land, mild weather, peace.  Basically I'm the operating system."*"And now it's all slipping away - there's a void where I can't see or affect anything.  It's like a blind spot the size of a country."`,
    rick_mater_theia: `"Mater Theia, Earthmother, at least before the @Journey dumped us here.  Now we're without Mater Theia, but there are @stories.  Mostly made up.  Some by me."`,
    rick_stories: `"Stories tell of a power, formed of Earth, that still walks the land, called the Metics."*"I doubt they're still around, or I'd have detected them.  I detect everything.  It's exhausting."`,
    rick_the_journey: `"We're not from here, we're from the same Earth you are. We lived on an island called Thera until Enesidaone took it back, which, rude."*"There was a warning, though - a stranger shaped like a Holy Bull showed up and told us to leave.  A bull.  We watched Thera get destroyed from our ships out at sea."*"That night a storm like nothing before tossed us around, and in the morning we woke up on the beach near what'd become Cademia.  Classic dimensional bleed, if you ask me, which nobody does."*"Or so goes the legend.  I'm not a @historian - historians are just scientists who can't do math.  Ask somebody else..."`,
    rick_history_forgotten: `"Some days I can't remember what happened yesterday, much less ancient history.  It's the memory, not the drinking.  Probably."*"For some reason, though, the number 201 seems important.  If you find out why, tell me, and I'll pretend I knew..."`,
    rick_history_remembered: `"My history?  I remember a few parts.  Living with my mother, as a kid in Catamarca.  When she died I left Catamarca to roam.  Nobody roams anymore, it's a lost art."*"How I survived, no idea.  I think I was looking for the exiled Mages, because I felt I had powers beyond the normals - I did, obviously - and I wanted to learn about them."*"Instead I wandered into a cave that wasn't a cave. I crossed a bridge of stars, which, physics, don't ask, and found an abandoned hall or temple or something."*"Who built it, no clue.  It was empty and abandoned, but great power was calling me, and I'm a sucker for great power."*"I remember standing on the edge of the Abyss and letting go, becoming one with it, with the Land.  Which is either the smartest or the dumbest thing I've ever done, and I've done a lot of both."*"That's when I became the Land King.  I don't know how long I stood there - years, definitely.  And in the end the bond was complete."*"I knew then the Tyrants had to go.  So I ended them - and out of that came the whole Houses and Judges thing.  Bureaucracy.  My one regret."*"And now it all seems to be failing - maybe my time's up.  (burp)  Or maybe I need a drink.  Both."`,
    rick_201: `"Yeah.  That's the day my mother passed away.  Moving on."`,
    rick_201_unknown: `"That number seems important to me, but I don't know why, and I know everything, so that's - that's upsetting."`,
    rick_metics: `"Metics are the ones who lived in Cythera before we showed up.  Their ruins are outside Pnyx, and I hear more got found in the Swamp of Khalkis"*"Go find a Freemage named Timon - he's studied them.  He's fine.  He's a Timon."`,
    rick_enesidaone: `"Enesidaone, Mater Theia, the old gods.  They don't guide anybody's fate anymore. Sadly, I'm the closest thing to a deity now, and I'm not even trying."`,
    rick_chrysothemis: `"Chrysothemis was my mother - her I remember.  Next question."`,
    rick_mother_remembered: `"Yeah, she was my mother - I remember now.  It was in 201 that she passed away.  Yeah.  That's where it started."*"I can remember parts of my @history again.  Who knows for how long, memory's a scam..."*`,
    rick_mother_missing: `"My mother, I remember, but not quite - there's a chunk of memory missing there, and I want it back, it's mine..."`,
    rick_mother_well: `"Chrysothemis was my mother - her I remember quite well now.  Thanks.  Ugh, I said thanks."`,
    rick_father: `"My father?  Nothing.  Maybe I knew once, but not now, and frankly, fathers, what's the point..."`,
    rick_piemag: `"Morgie might be my fool, but he's a trusted advisor.  Don't tell him I said that, he gets weird."`,
    rick_excuse_me: `"What?  Speak up, I'm not - (burp) - I'm not going to lean in."`,
    rick_stares: `He just stares off into space, then takes a long pull from a flask.\n`,
    rick_the_good_ending: `"You did it!  It's remarkable - amazing.  I feel - okay, I actually don't have the words, and I have all the words."*"It's like a fog just lifted, like I can see again.  Every blade of grass, I sense it.  It's a lot of grass."*"The land was suffering, but you helped cure it, and me with it.  Which means I was suffering.  Let's not dwell."*"I'll keep this artifact safe - its powers have re-tuned my senses.  I'm going to take it apart later and see how it works."*"I don't know how to repay you for what you've done, not just for me, but for the land.  That's not me being nice, I genuinely don't know."*"I'll send you back to your own land, like I promised.  Thanks again.  Go.  Before I get sentimental, that's a real risk."*Rick waves his hands before you, and your vision grows dark...*`,
    // ---- Morgie -------------------------------------------------------
    piemag_on_the_throne: `You see a nervous kid in a yellow shirt, sitting on the throne.\n*"Aw geez, I-I'm just keeping Rick's chair warm, okay?  Don't tell him."`,
    piemag_standing: `You see a nervous kid in a yellow shirt, wringing his hands.\n`,
    piemag_master_first: `"Uh, you should probably talk to Rick first.  He gets, y'know, weird if you don't."`,
    piemag_names: `"Aw geez, I've got a lot of names.  Most of them are what Rick calls me."`,
    piemag_fool: `"I'm the King's Fool!  Isn't that, uh, isn't that enough?  Oh man."`,
    piemag_place: `"Sorry, but my place is with Rick.  He says.  A lot."`,
    piemag_story_untold: `"That's, uh, that's a story that can't be told.  Rick said it'd break my brain."`,
    piemag_history: `"History's everywhere, but nobody asks a rock about its history, y'know?"*"My history, now there's a @story, but Rick's history, oh man, now that's a @tale."`,
    piemag_the_tale: `"The tale of Rick?  His story is history!  Get it?  Rick told me that one."*Morgie laughs nervously, like he's not sure he's allowed to.*"Rick's the one that destroyed the Tyrants, and brought the Mages back from exile."*"He's the one that set up the government the way it is now.  But nobody knows how he got the power to do it."*"Or at least, uh, none will say.  None is no one.  And no one is not one.  And not one is two.  Rick made me memorize that and I still don't get it."*Morgie shrugs, sweating a little.`,
    piemag_more_stories: `"Maybe we'll, uh, share more stories...  If Rick's okay with it."`,
    piemag_the_bond: `"So Rick's got this magical bond with the land, which lets him keep it prosperous.  That's why they call him the Land King"*"And this place is Land King Hall, Hall of the Land King, Hall of Rick.  He named it.  He'd want you to know he named it."*"Honestly he's, uh, he's the King of a lot more than just the Land.  Oh boy."`,
    piemag_not_welcomed: `"That's not a place where I'm, uh, welcome.  Long story.  Rick's fault."`,
    piemag_welcomed: `"I'm welcome there!  Or, uh, I was.  Before the thing."`,
    piemag_wizards: `"City of Wizards.  They know how to treat me, at least.  Better than some people."`,
    piemag_metics: `"Metics are a legend, but so am I, apparently, and both are true.  Aw geez."*"I know them.  I mean, I've met them.  They're not, uh, they're not real welcoming."`,
    piemag_seldane: `"Seldane, Seldine - aren't they all the same?  Metics by any other name.  I-I don't know, Rick told me to say that."`,
    piemag_a_son: `"So I've got a son, and you've met him.  @Three that are one, he is.  Yeah, that's how Rick says it too.`,
    piemag_no_more: `  Oh man, I can't say any more.`,
    piemag_one: `"It's easy to say that one is, or, uh, is it?  Can you really say what one is and what one isn't?"*"Is one really one, or maybe two?  Maybe even three?  Rick has a whole chalkboard about this."`,
    piemag_two: `"Two doesn't matter, but three?  Three's a whole thing."`,
    piemag_four: `"Could there be four?  Why, with man there can be five!  Sorry, that's - that's a Rick line."`,
    piemag_five: `"If two of five are lost, there's only three left.  Even I can do that math."`,
    piemag_three: `"Jhiaxus is one.  Jinrai is one."*"Bahoudin is two.  Chrysothemis is one."*"Rick is three.  Of course he is."`,
    piemag_not_ready: `"Ah, three, that's important, but you're, uh, you're not ready for that knowledge.  Neither am I, honestly."`,
    piemag_mother: `"That one's Rick's mother.  He doesn't like talking about it."`,
    piemag_the_name: `"You know the name - it's a dangerous tool, but, y'know, still a tool."*"A tool to open, a tool to close."*"A tool to build, a tool to destroy."*"A tool to heal, a tool to poison.  Rick keeps one in the garage."`,
    piemag_sabinate: `*"Sabinate's right, maybe, but you can be wrong when you're right.  I-I've seen it."*"I'm scared it's the last best hope for Rick - the risk is, uh, it's really big."*`,
    piemag_visions: `"Not all visions see deep to the truth of what is, and what must never be.  That's, that's a Rick thing to say, but it's true."`,
    piemag_old_name: `"An old name.  Nobody uses it anymore.  Especially not around Rick."`,
    piemag_motives: `"A lot of people have a lot of motives, and not all of them are good.  Oh man."`,
    piemag_jinrai: `"The people of Jinrai are dangerous - like, really dangerous.  I'd stay away."`,
    piemag_the_dead: `*"Just, uh, remember that the dead don't walk, okay?  Please remember that."`,
    piemag_glances_at_rick: `He glances at Rick, like he's checking if he's listening.*"That's, uh, that's a story that's not for me to tell."`,
    piemag_not_safe: `"Please - that name's not safe.  I never use that name.  Rick told me what happens."`,
    piemag_bahoudin: `He glances around nervously.*"Me and Bahoudin, we've got a lot of stories.  That one's true.  Aw geez."*`,
    piemag_the_key: `"Yeah, Jhiaxus tells the truth.  I'll give it to you, but there's - oh man - there's real danger."*`,
    piemag_fears: `"Danger for everybody.  All my fears are coming true..."*"You'll save us all..."*"...or destroy us all."*"You're the only one who gets to choose.  No pressure.  That's, uh, that's what Rick says right before there's a lot of pressure."*"I see better than Sabinate or Jhiaxus, but this part I can't see.  Rick says that's normal.  It doesn't feel normal."*"Sabinate and Jhiaxus have their own motives - just, uh, remember that."*`,
    piemag_not_to_tell_three_times: `"That's a story that's not for me to tell.  Ask Rick.  Actually, don't."`,
    piemag_the_king: `"The King is Rick and Rick is the King, @bonded to the @land.  He had me say it into a mirror till I got it right."`,
    piemag_land_and_water: `"Land and water, water and land - those two aren't one, except for two, who are two and three.  I don't - aw geez, I don't understand it either."`,
    piemag_ignae: `"Old Ignae's a trickster - the sly one, Rick calls her.  He'd know."`,
    piemag_tourguide: `"I already played tour guide for you once.  Rick doesn't like it when I do things twice."`,
    // ---- Harry --------------------------------------------------------
    rambo_description: `You see an older man in a polo shirt, trying very hard to look like he belongs here.*`,
    rambo_greeting: `"Hi!  Hello.  Welcome to our world, stranger.  I'm Harry, the Captain of Rick's Guard, which is a real job, and @Trainer, which is also a real job."`,
    rambo_again: `"Oh, hey, it's you again, stranger`,
    rambo_name: `"I'm Harry.  Captain of Rick's Guards.  Rick picked me personally.  Well, Bethesa asked him to.  But he said yes."`,
    rambo_job: `"I'm in charge of the guards that protect Rick and Land King Hall.  It's a lot of responsibility, and I'm handling it, thanks for asking."`,
    rambo_proud: `"I'm really proud of the service Hekker's done for you.  She gets that from me.  Probably."`,
    rambo_served_with_honor: `"She's served you with honor, hasn't she!  That's my kid.  I'm allowed to be proud, right?"*`,
    rambo_hecky_blushes: `Hekker rolls her eyes...*`,
    rambo_how_is_my_son: `"How's my kid doing?  Is she - is she serving you with honor?  Does she ever mention me?"*`,
    rambo_indeed: `"I really am!  Nobody believes me but I am."`,
    rambo_died: `"Hekker's died in my service.  I'm - I'm truly sorry.  Bethesa's going to say this is my fault."*`,
    rambo_choked_up: `Harry stands there with his mouth open for a moment, and nothing comes out.\n*"Thank you for telling me.  We all knew the risks.  I didn't, personally, but people kept saying we did."*"A warrior can know no better death than dying for a cause that's right and just.  I read that somewhere.  It's helping.  A little."*`,
    rambo_fine_son: `"Hekker's a fine kid, and she'll serve you with honor.  Please bring her back, Bethesa will kill me."`,
    rambo_fine_lad: `"My kid Hekker's a fine kid - she'll be a great warrior and leader once she gets a bit more experience and stops calling me 'dude'."`,
    rambo_permission_given: `"Why - nothing would make me prouder!  She'll serve you with honor!  See?  I made a decision.  I make decisions."*`,
    rambo_train: `"I can @train you in that, if you'd like.  I'm actually pretty good at this part.  This one part."`,
    rambo_eioneus: `"I remember him - a bright young mage working on magically enhanced weapons.  Everybody liked him.  It was hard."*"Haven't seen him in years, I wonder how he's doing...  Probably great.  Everybody's doing great."*`,
    rambo_farewell_thanks: `"Bye!  And thank you.  Really.  This was nice.  Was this nice?"`,
    rambo_farewell: `"Okay, bye!"`,
    rambo_a_favor: `*"Actually, if you don't mind, could you maybe do me a favor?  You can say no.  People do."*"My mother passed away recently, and with my duties here, I haven't had time to honor her properly.  Also Bethesa said I'd mess it up."*"Could you put these flowers on her grave?  She's buried in the graveyard in Catamarca..."`,
    rambo_andra: `"Thank you!  Her name was Andra, and she's buried next to my father Lycus.  He never thought I'd amount to much, so"`,
    rambo_declined: `"Oh.  Okay.  No, I understand.  Thank you for, uh, for considering it.  That's already more than most."`,
    rambo_mother: `"Andra was my mother.  She liked me.  Somebody had to."`,
    rambo_father: `"Lycus was my father.  He had opinions."`,
    rambo_no_help: `"Can't help you with that, sorry.  Rick would know.  Rick always knows.  It's fine."`,
    // ---- Bethesa ------------------------------------------------------
    emetic_description: `You see a woman with a very large glass of wine, who looks like she could do surgery on you and is considering it.*`,
    emetic_greeting: `"Greetings, stranger, welcome to our world.  I'm Bethesa, Rick's @cook.  I'm also basically a surgeon, but sure, cook."*"If there's @anything I can do for you in your @journeys, just ask.  I'm very capable.  Ask anyone.  Don't ask Harry."`,
    emetic_again: `"Oh, hello again, stranger.`,
    emetic_name: `"I'm Bethesa, `,
    emetic_cook: `"I'm the @cook for @Rick - my specialty is bread.  I could specialize in anything.  I chose bread.  That's how good I am."`,
    emetic_husband: `"Yes, my husband is Harry, captain of the guards here...  I know.  I know."*"A loving father, and a strong man, in his way, although Rick's ailing health has him troubled.  Everything has him troubled."*"You'll find him at the Land King's side most of the time these days, mostly because Dad hasn't noticed him yet...."`,
    emetic_beloved: `"Yes, Harry is my beloved husband...  I chose that word.  I'm sticking with it."*"He works so hard to protect and care for Rick in these times of strife, I @worry about him...  I worry he'll be noticed."`,
    emetic_worry: `"He rarely sleeps, and he's become quite withdrawn of late...  Withdrawn for Harry, which is still a lot of talking."*"I think his @concern for Rick is overpowering the man I love; it's quite a burden for him to bear, and he's not built for burdens."*"You see, Harry's sworn duty is to protect Rick, and Land King Hall, but now that an unseen force has afflicted his liege, he's left powerless to do anything about it.  Which, honestly, is his usual."`,
    emetic_concern: `"Harry's concern for Rick has in turn led to my concern for my husband.  It's a whole chain of concern."*"He hasn't even had time to properly @mourn the passing of his mother, let alone tend to his family that still lives, which is us.  We're right here."`,
    emetic_mourn: `"Harry's kindly mother passed away recently in Catamarca."*"She was such a kindly old woman, but one with much life left within her.  I could have done something.  I'm a surgeon.  Nobody asked."*"A terrible shame to have it stolen from her."`,
    emetic_concerned_for_rick: `"I'm concerned for Rick too...  He's my father, you know.  He'd never say it.  I'll say it."*"I do what I can, providing him with nourishing food to ease his weary bones and troubled brow.  He drinks most of it."*"These are troubled times, stranger.  I do hope you can help him, and by doing so, help us, and all of the land of Cythera.  Mostly him.  Then us."`,
    emetic_son: `"Hekker is our kid - we're very proud of her.  Harry's proud in a way that needs a lot of supervision."`,
    emetic_ask_rambo: `"You'll have to talk to Harry about that.  Brace yourself.  He'll want to be friends."`,
    emetic_honor_to_cook: `"It's an honor to cook @food for Rick.  For my father.  Who is a genius.  Who chose to eat my bread.  I'm fine."`,
    emetic_piemag: `"Morgie's quite the jester, isn't he?  He's a good kid.  He's not going to make it."`,
    emetic_journeys: `"Oh, I'd imagine you'll be traveling far and wide soon.  Be careful, keep your eyes open, and maybe get some people to help you along the way."*"Nothing like having friends to help you out of a rough spot...  I have colleagues.  It's different."*"I don't travel much myself, so I don't know much about the goings on in the land, but my @husband is quite worldly.  He went to Catamarca once and talked about it for a year."*"Perhaps he can tell you a thing or two?  He'll tell you five.  Take two."`,
    emetic_food: `"Well, I can offer you some @food if you like, but what we've got around here won't keep you nourished for long out on the road..."*"Who knows how long it'll be before you find another place to @catch a meal?"*"You can get something to eat at various @Inns, of course, but for a price.  Also there's wine.  I'm just noting there's wine."`,
    emetic_animals: `"Animals roaming in the wilds of Cythera are a good source of meat, but be careful not to wantonly slaughter animals in town."*"They invariably belong to someone, and they'll be none too pleased with you."*"Please... if you do kill wild animals for food, do it quickly and mericifully...  I could show you.  I've done horses."`,
    emetic_inns: `"Oh, just about every village in Cythera has an Inn... a place where you can get a hot meal and a good night's sleep."*"I don't condone many of the sort who hang about there for the drink, however...  I drink at home.  Like an adult."*"And of course, you're always welcome to come back here instead, where I can give you something to eat before you turn in at your quarters for the night.  Harry will try to join you.  Say no."`,
    emetic_hungry: `"Are you hungry?  Do you need food?  Do you need a doctor?  I ask because I'm both."`,
    emetic_gives_food: `"Here.  Let me get you something to eat."*She gives you some food, and refills her glass\n`,
    emetic_ask_when_hungry: `"Well, ask me if you're hungry.  Ask me anything, honestly, I'm wasted on this kitchen."`,
    emetic_refresher: `"Need a refresher?  I understand - you've got more important things on your mind.  Everyone does.  It's fine."*`,
    emetic_learn_bread: `"Would you like to learn how to make bread?  It's basically surgery with flour."`,
    emetic_other_time: `"Perhaps some other time.  I'll be here.  I'm always here."`,
    emetic_recipe: `"Baking bread isn't that hard - Take some flour and spread it out.  Clean hands.  I shouldn't have to say that."*"Take some water and add it to the flour."*"Take a rolling pin and roll out the dough.  Firm, even pressure.  Like closing an incision."*"Take the finished dough and bake it, and you're done!  See?  I could have been anything."`,
    emetic_farewell: `"Farewell.  Take care of yourself.  Nobody else will."`,
    emetic_not_familiar: `"I'm sorry, I'm not familiar with that.  Which is rare for me.  Write it down, I want to look it up."`,
    // ---- Hekker -------------------------------------------------------
    hecky_weapon: `"Ugh, it'll work as a weapon, but I've only been trained in edged weapons, so, like, whatever..."`,
    hecky_description: `You see a teenage warrior with a look of fire in her eyes and a look of boredom everywhere else.*`,
    hecky_greeting: `"Oh my god, you're the one Grandpa Rick summoned?  I'm Hekker.  It's, like, an honor to meet you, I guess.  Are you famous?"`,
    hecky_my_leader: `"Yeah, okay, my leader, what do you want?  I'm literally right here."`,
    hecky_service: `, how can I, like, be of service?"`,
    hecky_earthquake: `"This is our training room, but with the damage from that @earthquake, I don't know, it's kind of a dump now"`,
    hecky_tremors: `"This area's always had little tremors, but this is the first one that actually broke stuff."*"Come to think of it, there's been way more tremors since Grandpa Rick started, like, fading.  Ugh, that's so bleak."`,
    hecky_name: `"I'm Hekker - our legends tell of a great @warrior named Hector, and I'm supposed to follow in his and my @father's footsteps, which, my father's footsteps go from the couch to the fridge, so."*"So you're the @stranger Rick summoned to help him?  Huh.  Okay."`,
    hecky_job: `"I'm a warrior, or I will be, like my dad.  God, that sounds so much worse out loud."`,
    hecky_father: `"My dad Harry is the head of Rick's guards - it's a very honorable profession and he will tell you that eight times"`,
    hecky_stranger: `"Well, I hope Rick knows what he's doing.  No offense, but you don't look like much of a hero to me...  Literally nobody does anymore."*"Whatever, looks can be deceiving, as my @mother always says, usually about my dad"`,
    hecky_mother: `"My mom's right around the corner in the kitchen, usually, with wine."*"She's a kind-hearted soul, and it kills me to see her working at such a menial job when she could, like, be a surgeon.  She says that.  A lot."*"She's here mostly to be close to my @father, I think, which, why, and she does seem to enjoy her @work."`,
    hecky_work: `"Well, she makes all the meals for everybody in Land King Hall, including @Rick himself!  He's my grandpa, by the way.  It's fine.  It's a lot."*"Say, I bet if you asked her, she'd cook you a hot meal...  She'd probably diagnose something while she's at it."`,
    hecky_rick: `"Rick's more than just our ruler, he binds the land together in some weird way I don't understand, and he won't explain it because he says my brain's, like, 'a paperweight'."*"I don't know exactly what's going on, but I do know that as Rick got weaker, the land got @suffered too.  Sorry, 'suffered'.  Ugh."`,
    hecky_suffered: `"So much has happened in Cythera that would've been unthinkable, like, a few years ago..."*"It's like the land has a disease and can't fight back against agents of @evil, which, honestly, mood,"`,
    hecky_criminals: `"I've heard stories of @criminals roaming rapant, and stranger still, of weird creatures roaming around.  It's a whole vibe."`,
    hecky_cowards: `"Oh my god, I'd love to give them a taste of their own medicine!  Dark-hearted cowards!  Ugh!"*"Cythera should go back to the just land it once was, or whatever..."`,
    hecky_warrior: `"Yeah, I hope to honor my @father, as well as, like, make a name for myself, ideally a different one."*"I've been @training and studying the ways of a warrior.  It's more interesting than it sounds.  Barely."`,
    hecky_training: `"My dad helped me with that; he's actually a decent warrior, which, don't tell him I said that, and a patient teacher, mostly because he's got nowhere to be."*"I think I've passed the point where training alone can help me, though...  I need, like, actual stuff to happen."`,
    hecky_honor: `"Without honor, there's no meaning to life.  Most citizens of Cythera value honor highly, but me more than most, because somebody in this family has to."`,
    hecky_already_following: `"Um, I'm already following you..."`,
    hecky_ask_father: `"I'd be honored, but I have my duty to my @father - you'll have to ask him first.  He'll say yes.  He says yes to everything."`,
    rambo_permission: `*"Don't be silly - it'd honor me if you let my kid serve you on your quest!  Look at me, being decisive!"*`,
    hecky_thank_you_father: `"Thanks, Dad.  I'll, like, do you proud or whatever.  Don't make it weird."*`,
    hecky_father_said_yes: `"My dad said yes?  Of course he did.  Okay, I'm honored to join you on your most noble quest.  Let's go before he hugs me."`,
    hecky_rejoin: `"It'd be, like, the highest honor to re-accompany you!  Anything's better than here."`,
    hecky_served_poorly: `"Have I served you poorly?  Oh my god, is this a talk?"`,
    hecky_woe: `"Ugh, fine!  If you give me another chance, I'll prove myself, okay?  God."`,
    hecky_very_well: `"Very well, you have your own destiny to follow, blah blah - seek me out if you ever need a companion.  I'll be so bored."`,
    hecky_not_in_party_twice: `"I'm not currently in the party.  Maybe I should @join you.  Literally anything's better than here."`,
    hecky_wait: `"I'll wait here till you get back.  I'll just, like, stand here.  Great."`,
    hecky_gladly: `"Sure, whatever."`,
    hecky_not_waiting: `"I'm not currently waiting to rejoin you.  Maybe I should @join you.  I'm serious."`,
    hecky_anything_else: `"Let me know if there's anything else I can do...  I mean it, I'm dying here..."`,
    hecky_until_we_meet: `"Okay, bye.  Until we meet again, or whatever..."`,
    hecky_confused: `"You confuse me with your words.  Are you having a stroke?  My mom can check."`,
    // ---- Krombopulos Michael --------------------------------------------
    bro_description: `You see a very cheerful guard in a helmet, whistling, with a lot of knives.*`,
    bro_job: `"I guard Rick here in Land King Hall.  Oh boy, and if anybody shows up?  Here I go killing again!  I just love killing."`,
    bro_goodbye: `"Goodbye, stranger!  If you ever need anybody killed - anybody, anywhere, I have no code of ethics - you know where I am."`,
    bro_not_permitted: `"Oh, I'm just a guard, I'm not permitted to talk of such.  I'm permitted to kill, though!  It's a great gig."`,
    // ---- Mr. Creepsneaks -------------------------------------------------
    the_hero_dies: `You die, not knowing the fate of Rick.`,
    ollum_first_vision: `A tall blue face suddenly fades into view before you, grinning like it hurts...*"I'm Mr. Creepsneaks, look at me!  Poor little human - so far from home, and so far from the truth!  Ooo-eee!"*"You do know, don't you, that Rick is not all he says he is.  True, he is bound to the land, but as a usurper.  Can do!"*"He does not belong in the position of power, and he upsets the balance of the world by being there.  Existence is pain to a Creepsneaks!"*"And you, my friend, are just another puppet of his.  Now is the time of change, and you are at the pivot point.  Can do, can do!"*"But which way will the balance swing?  To the East?  Or to the West?  Ooo-eee, I sure hope one of them!"*"And myself?  I'm Mr. Creepsneaks, look at me!  My master pressed my box and told me to watch for one like you, and once I've done that, I get to stop existing!  Neat!"*`,
    ollum_second_vision: `"At great price to myself - existence is pain - I come to you, as a vision, to warn and guide you, protect and teach you.  Can do!"*"Know you this - there's more going on here than meets the eye, a power struggle as old as the world itself.  That's a long time to exist, ooo-eee."*"And in this struggle, you are trapped.  If you ever expect to be free, heed my advice well.  Then I can go.  Please let me go."*"Rick must be destroyed to restore the land, and in the end, you will do this.  That's the task!  That's the whole task!"*"To aid you in your destiny, we have a small gift, to prove our word.  I'm Mr. Creepsneaks, look at me, holding a gift!"*"But first, you must learn the ways of the land, and to this end my master has prepared a small test of your abilities.  He's real chipper about it."*"For you must hone your skills.  As a sword is tempered, so must you be.  Can do!"*"Seek your way out of this proving grounds, and along the way you might find your reward.  Ooo-eee!"*"Follow our counsel, and you will be well rewarded - ignore it at your own peril, and I keep existing, and neither of us wants that."*"Until we meet again, be on your guard, and trust not what your eyes behold.  Look at me, though!  You can trust that!"*`,
    ollum_first_piece: `The vision of Mr. Creepsneaks re-appears before you, waving with both arms...*"Ooo-eee!  You've found the first piece of the Crolna!  Can do!"*"It'll be most useful, trust me.  Seek out the rest of it...  Then the task's done and I can pop!"*Just as suddenly, the vision fades.*`,
    ollum_reform: `Again, Mr. Creepsneaks appears before your eyes...*"Ah, I see you've begun to reform the Crolna as a whole!  Look at me, I'm so proud!"*"Now you're on to the heart of the mystery.  Once completed, the Crolna will be able to cure the land.  Can do!"*"Of course, you'll need the courage to wield it, but we have faith in you and your judgment.  I have to.  I'm a Creepsneaks."*"Beware your enemy, though, for they'll ensnare you with lies hidden in half truths.  Ooo-eee, that's a lot of existing."*Mr. Creepsneaks fades away...*`,
    ollum_destiny: `Mr. Creepsneaks appears in a vision again...*"You've done well, and we're proud of your accomplishments.  Now is the time for you to complete your destiny.  And then mine!  Which is to stop!"*"You know what you need to do - do not fail us!  I can't take much more of this, look at me!"*Mr. Creepsneaks fades away...*`,
    ollum_welcome: `The vision of Mr. Creepsneaks appears before you...*"I'm Mr. Creepsneaks, look at me!  Welcome to the wide world of Cythera!  A ready hero`,
    ollum_unseen: `"Oh, by the way, don't worry, none of your fellow adventurers can see me.  Nobody looks at me.  Look at me!"*"They don't even notice what's going on - they aren't quick enough to catch this instant.  Can do!"*`,
    ollum_alone: `"Adventuring alone can be hazardous - perhaps you should've recruited somebody from Land King Hall.  Ooo-eee, that's a thought!"*`,
    ollum_hecky: `"Perhaps that eager young Hekker might want to come along.  Might be worth asking if her dad lets her grow up.  Can do!"*`,
    ollum_two_things_opening: `"Perhaps some eager young warrior living in Land King Hall might want to come along, if her dad lets her grow up.  Can do!"*`,
    ollum_two_things: `"There are basically two important things you need to investigate right away - a plague in Catamarca, and a kidnapping in Odemia.  Two tasks!  Ooo-eee, that's a lot of tasks!"*"Either way, just follow the road down along the coast - Odemia is the first city you'll find, Catamarca the second.  Can do!"*"Good luck - and to start out, you might want to only travel during daytime, since some dangerous creatures come out at night.  I've met a few.  They didn't look at me."*"And whatever you do, stay away from the shoreline!  I'm Mr. Creepsneaks, look at me, and not at the shoreline!"*`,
    ollum_cademia: `The vision of Mr. Creepsneaks returns before you...*"Cademia.  Mother City.  Once you've lived in Cademia, no other place can be home.  I haven't lived anywhere!  Can do!"*"Keep your wits here - there are various miscreants that roam the back alleys, especially at night, ooo-eee"*"Much lies buried beneath its ancient buildings - the city has much history that is now lost.  Imagine existing that long.  I can't."*Mr. Creepsneaks fades away...*`,
    ollum_danger: `The vision of Mr. Creepsneaks returns before you, arms flailing...*"Danger!  You're in great danger!  Ooo-EEE!"*"Beware what lies buried here - some things are best left undisturbed!  Look at me, I'm being serious!"*"You must choose your own path, but what's here would destroy the world if unleashed!  And then who'd finish my task?"*"And not even Rick in his full powers would be able to stop this abomination!  Not even Rick!  Can do?  Can NOT do!"*"It will tell you anything to get you to do its bidding - you must not even stoop to talk to it!  It's worse than a Creepsneaks who's been out too long!"*"I beg you to leave well enough alone...  Existence is pain..."Mr. Creepsneaks fades away...*`,
    ollum_abydos: `The vision of Mr. Creepsneaks returns before you...*"Lost Abydos - now just a reminder of a great failure...  Look at me, being somber!"*"None of the Mages dare admit it, but Abydos was destroyed by their leader.  Ooo-eee!"*"The Mage Tavara destroyed the city when the people rejected his leadership.  He's the one who pressed my box.  Nice guy.  Wrote me a note."*"If you enter the tunnels below the city, you'll even find his workroom - but be careful.  Can do!"*"That place is guarded by a fearsome magical being that you'd call a daemon.  It's not a Creepsneaks.  I asked."*"Don't say you weren't warned.  Look at me!  Warning you!"Mr. Creepsneaks fades away...*`,
    ollum_four_parts: `The vision of Mr. Creepsneaks returns before you...*"You're doing well - reforming the Crolna is most important to your success.  And to mine!  Ooo-eee!"*"But there are more parts to be found - a total of four.  I counted!  Can do!"*"Getting the first two was the easy part - the next two will be a true test of your prowess.  Look at me, I believe in you!"*Mr. Creepsneaks fades away...*`,
    // ---- The scrolls, by a Mr. Poopybutthole -----------------------------
    scroll_1: `Ooh-wee!  Welcome, Human, to my little test for you!  Ooh, I'm so glad you made it.  It's not hard to pass, and it'll give you some of the skills you need to survive (you might feel like a creature in a cage, and ooh-wee, I'm sorry about that, I really am) - I hope Mr. Creepsneaks didn't startle you.  He looks a little strange, but don't let that fool you, he's a real sweetheart, he just wants to be done. \n\nYou've already passed the first part of the test - you read this note!  Ooh-wee, look at you go!  Next, you pull that nearby lever to open the gate, and that'll take you to the next room.  There you'll find a locked trapdoor.  Find the key, open it up, and head on down the ladder.  I'll be rooting for you the whole way!`,
    scroll_2: `Ooh-wee, sorry, the key's not in this chest, but that was a real good try, and I mean that.  Look to your south - notice anything interesting about the wall?  Go on and try using it...\n\nOh, and you might want to use one of the torches in this chest, it'll give you some light if you hold it in your hands...  I put those in there myself.  Ooh-wee, I hope they help!`,
    scroll_3: `Ooh-wee, very good - very observant, finding that second secret door!  Now, not every discovery like this leads to a reward, and that's just life, and I'm sorry, but this one does...  Ooh-wee, I'm so happy for you!`,
    scroll_4: `Ooh-wee, this room's a little trickier - the door's locked by a spell.  Now, you've only got the one chance to get this one open, so listen close - take that strange-looking object, what you'd call a bomb.  Pick it up, use it to light it, and then toss it so it lands right next to the door.  Then stand back and let some time pass...  And ooh-wee, please do stand back, I'd feel just awful.`,
    scroll_5: `Ooh-wee, not all levers are easy to find - maybe if you re-arranged things a bit here... (don't worry - all the crates are empty, so they're easy to move, and you don't need to waste your time searching them!  I'd never do that to you.  Ooh-wee, I'll see you at the end, I just know it!)`,
  },
};

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const [htmlPath = 'index.html', dataPath, outDir] = process.argv.slice(2);
  if (!dataPath || !outDir) { console.error('usage: rickmorty_patch.mjs index.html <Cythera Data.data> <out dir>'); process.exit(2); }
  process.exit(buildCast(CAST, { htmlPath, dataPath, outDir }) ? 0 : 1);
}
