#!/usr/bin/env node
/* A builder, not a check: the text fixes, and on top of them a voice for
   each of the people of Land King Hall, every line they speak, with new
   names. (24 September 2026, at the maintainer's word; a variant for fun.)

   Usage: node utilities/voices_patch.mjs index.html "<Cythera Data.data>" <out dir>

   Alaric is Rick, who also answers to Al, a surfer; Magpie is Piemag and
   speaks as Yoda does; Omen is Ollum and speaks as Gollum does; Hector is
   Hecky, an infant who worships his daddy; Hadrian is RAMBO; Emesa is
   Emetic, who loathes being asked for flatbread and bakes it foul on
   purpose; the hall's guard is LKH Bro, from the gym; and the scrolls of
   the Test, which the game's own text gives to the mage Tavara (Omen names
   him, and the Test's notes speak of Omen as their author's creature), are
   villainy without restraint.

   How it holds together: each spoken line is replaced whole, matched as the
   text fixes leave it, keeping its click marks, line breaks, the fragments
   the script joins mid-sentence and every highlighted @word, since a
   highlighted word must still begin with a keyword the script answers. The
   names change in the name table (what is drawn over a head), in every
   mention across every script, and in the keyword lists, which gain the new
   name beside the old so that either can be typed: "alar" keeps working and
   "rick" joins it. "Al" is not a keyword, since typed words match by their
   first letters and "al" would catch "alchemy". Omen has no keyword; the
   guard's is "guar" and stays. */
import {fileURLToPath} from 'node:url';
import {buildPatch} from './patch_build.mjs';
import {T, textFixEdits} from './text_fixes_patch.mjs';

const R = (what, resid, find, replace) => T(what, resid, find, replace, 1);
const NUL = '\u0000';

// ---- Rick (Alaric), 0x1802 -------------------------------------------------
const RICK = [
  R('Rick: description', 0x1802, `Before you stands an older, dignified gentleman`, `Before you stands a sun-bleached older dude with a totally gnarly tan`),
  R('Rick: desperate', 0x1802, `, but with a look of desperation.`, `, but, like, seriously bummed out.`),
  R('Rick: satisfied', 0x1802, `, with a look of satisfaction.`, `, looking totally stoked.`),
  R('Rick: relieved', 0x1802, `, with a look of relief and calm.`, `, looking mellow and, like, at one with the universe, man.`),
  R('Rick: the dark ending', 0x1802, `Just before your vision fades completely, the face of Alaric wavers.*`, `Just before your vision fades completely, the face of Rick wavers, and the vibe goes seriously dark.*`),
  R('Rick: possessed', 0x1802, `"Yes, thank you foolish mortal - without you, we never would have gained control of he who was once Alaric."*"With the powers of the Crolna, Land King Hall and all humanity behind us, we shall make short work of the Seldane."*"And then we can rid ourselves of the humans as well - our victory has been sealed."*`,
    `"Yes, thank you, foolish mortal - without you, we never would have gained control of he who was once Rick."*"With the powers of the Crolna, Land King Hall and all humanity behind us, we shall make short work of the Seldane."*"And then we can rid ourselves of the humans as well - dude, our victory is, like, totally sealed."*`),
  R('Rick: Piemag vision', 0x1802, `Just before it fades completely, the vision Magpie appears before you.`, `Just before it fades completely, the vision of Piemag appears before you.`),
  R('Rick: Bahoudin thanks', 0x1802, `*"Bahoudin thanks you for curing Alaric.  Were Alaric's mother, Chrysothemis, alive today, she would thank you."*"Alas, she is not.  Still, her husband, father of Alaric, Bahoudin, thanks you for saving his son."*`,
    `*"Thank you for curing Rick, Bahoudin does.  Alive today were Rick's mother, Chrysothemis, thank you she would, hmm."*"Alas, alive she is not.  Still, her husband, father of Rick, Bahoudin, thank you he does, for saving his son.  Yes."*`),
  R('Rick: first speech', 0x1802, `"Ah - good, you are about.  We were worried that you were harmed."*"I suppose I should explain what happened.  My name is Alaric and you are now in the land of @Cythera."*"You were summoned in a final, desperate attempt to save Cythera and its ruler from chaos and madness."*"I am that ruler, and I have a special @bond with the land and the people of Cythera.  For over two hundred years I have used my magic to keep it prosperous."*"Unfortunately, over the past couple of years, my power has waned, and with it, Cythera has started slipping into chaos."*"It is as if that bond were dissolving, the land somehow changing. I do not understand it."*"The more impotent I become, the more frustrating it is to see it all slipping away, like waking from a dream..."*"I have trusted the fates to summon an outsider, from @Mater Theia herself, for only an outsider will be able to see through this cloud that blocks my vision."*"You, of course, are that outsider.  Do not think that I did this on a whim - it has cost me most of my remaining power to do so."*"I must trust you to help me.  I am sorry for the danger this costs you, but you are my, and Cythera's, last chance."`,
    `"Duuude - you're up!  Righteous.  We were, like, majorly worried you got wiped out."*"So, okay, I should probably explain the sitch.  Name's Rick - or Al, whatever, bro, I answer to both - and you are now in the land of @Cythera.  Gnarly, right?"*"You got summoned in a final, desperate, hail-Mary kinda move to save Cythera and its ruler from total chaos and, like, madness."*"I'm that ruler, dude, and I've got this special @bond with the land and the people of Cythera.  For over two hundred years I've used my magic to keep the whole scene mellow and prosperous."*"Bummer is, the last coupla years my mojo's been fading, and with it Cythera's started, like, wiping out into chaos."*"It's like that bond is dissolving, the land's changing somehow. I don't get it, man."*"The more impotent I get, the more it harshes my mellow to watch it all slip away, like waking up from a totally epic dream..."*"So I trusted the fates to summon an outsider, from @Mater Theia herself, 'cause only an outsider can see through this fog that's, like, blocking my vision."*"You, obviously, are that outsider.  Don't think I did this on a whim, bro - it cost me most of my remaining power to pull it off."*"I gotta trust you to help me.  Sorry about the danger and all, but you're my, and Cythera's, last chance.  No pressure, dude."`),
  R('Rick: rude of me', 0x1802, `"I am Alaric - did I tell you before?  I am sorry, how rude of me.\n"`, `"I'm Rick - or Al, take your pick - did I tell you already?  My bad, dude, totally rude of me.\n"`),
  R('Rick: keeper', 0x1802, `"I am keeper of the land of Cythera,`, `"I'm, like, the keeper of the land of Cythera,`),
  R('Rick: stranger', 0x1802, ` though at times I feel like a stranger."`, ` though some days I feel like a total kook, man."`),
  R('Rick: look you over', 0x1802, `"Hm, let's look you over..."*`, `"Hm, lemme check you out, dude..."*`),
  R('Rick: that should help', 0x1802, `"There, that should help..."`, `"There, that should help.  Sweet."`),
  R('Rick: good shape', 0x1802, `"You look in pretty good shape as it is."`, `"Dude, you're looking totally shredded as it is."`),
  R('Rick: stained', 0x1802, `"I'm sorry, but your soul is too stained for me to be able to cleanse it."`, `"Sorry, bro, but your soul's got way too much bad karma for me to hose off."`),
  R('Rick: register', 0x1802, `"Sorry, I can't help you until you registered this software."`, `"Sorry, dude, can't help you till you've registered this software.  Not cool, man."`),
  R('Rick: no experience', 0x1802, `"You don't have enough experience for further training."`, `"Dude, you haven't logged enough waves for more training yet."`),
  R('Rick: amulet', 0x1802, `"Here, take this amulet - it has my symbol on it.  When worn around your neck, it will save your life if you die."*"You can also use it to bring back a companion from the halls of death, but be warned, it has a limited number of uses."*He gives you an amulet on a gold chain.*`,
    `"Here, take this amulet, bro - it's got my symbol on it.  Wear it around your neck and it'll save your life if you, like, totally wipe out."*"You can also use it to bring a buddy back from the halls of death, but heads up, it's only got so many charges in it."*He gives you an amulet on a gold chain, and a shaka.*`),
  R('Rick: quarters', 0x1802, `*"I've got some quarters set up for you - Magpie will show you around."*`, `*"I got some quarters set up for you, dude - Piemag will show you around."*`),
  R('Piemag: follow', 0x1802, `"Follow Magpie, you should."*`, `"Follow Piemag, you should.  Hmm, yes."*`),
  R('Piemag: the library', 0x1802, `Magpie points to the end of the hall to the north.*"At the end of the hall, the Library is."*"Much learning can be found in there, from the books written by elders.  Do you well it might to learn."*`,
    `Piemag points to the end of the hall to the north.*"At the end of the hall, the Library is.  Yes."*"Much learning, in there, found can be, from the books by elders written.  Learn, you must.  Do you well, it might, hmm."*`),
  R('Piemag: the quarters', 0x1802, `"These are quarters for you.  Provisions in there are."*"The things in your quarters are yours, serve you well they shall."*"But be careful not to steal from others.  Cythera is an honorable land, and such deeds will serve you ill."*Magpie looks around quickly.*"Magpie is the fool, but even Magpie knows your journey will be dangerous, young one."*"Good it would do you to learn what you can.  Important visitors come and go, but you are unique."*"Demodocus stays across the hall, for the nonce.  Talk with him, Magpie would, would that Magpie be you."*"Also, one might ask around to see if somebody would like to @join you on your quest..."`,
    `"Quarters for you, these are.  Provisions, in there, are."*"Yours, the things in your quarters are.  Serve you well, they shall."*"But steal from others, you must not.  Honorable, Cythera is.  Serve you ill, such deeds will.  Yes, hmm."*Piemag looks around quickly.*"The fool, Piemag is.  But even Piemag knows: dangerous, your journey will be, young one."*"Learn what you can, you should.  Come and go, important visitors do.  But unique, you are."*"Across the hall, for the nonce, Demodocus stays.  Talk with him, Piemag would, were Piemag you."*"Also, ask around, one might, to see if somebody would like to @join you on your quest, hmm..."`),
  R('Rick: help me', 0x1802, `"Please, do what you can to help me."`, `"Please, dude, do what you can to help me out.  I'd be so stoked."`),
  R('Rick: Odemia', 0x1802, `"Odemia is the closest city - travel east, staying along the coast."`, `"Odemia's the closest city, bro - head east and just, like, hug the coast."`),
  R('Rick: the land', 0x1802, `"Yes, Cythera is the land."`, `"Yeah, dude, Cythera is the land.  Whoa."`),
  R('Rick: one again', 0x1802, `"I am as one with the land again, thanks to you."`, `"I'm, like, totally one with the land again, thanks to you, bro.  Cowabunga."`),
  R('Rick: the bond', 0x1802, `"I am, or was, at one with the land and its people.  I have provided all the basic needs of its people - a bountiful land, mild weather, and peace for its people."*"But now it all seems to be slipping away - a void where I can neither see nor affect."`,
    `"I am, or like, was, at one with the land and its people, man.  I've provided all their basic needs - a bountiful land, epic mild weather, and peace, dude, peace."*"But now it all seems to be slipping away - a void where I can't see squat or do squat.  Total bummer."`),
  R('Rick: Mater Theia', 0x1802, `"Mater Theia, Earthmother, at least before the @Journey brought us here.  Now we are without Mater Theia, but there are @stories."`, `"Mater Theia, Earthmother, dude, at least before the @Journey brought us here.  Now we're, like, without Mater Theia, but there are @stories, bro."`),
  R('Rick: stories', 0x1802, `"Stories tell of a power, formed of Earth, which still walks the land, whom we call Metics."*"However, I doubt that they still live, or I should have been able to detect their presence."`,
    `"Stories tell of a power, formed of Earth, that still walks the land, who we call Metics.  Gnarly, right?"*"But I doubt they're still around, or I'd have picked up their vibe, man."`),
  R('Rick: the journey', 0x1802, `"We are not from this place, but from the same Earth that you are. We lived on an island called Thera, until Enesidaone reclaimed it."*"But that was not without warning, for a stranger, in the form of the Holy Bull appeared, telling us to flee.  We saw Thera destroyed from the safety of our ships at sea."*"That night a storm such as has never been before tossed us about, until in the morning when we woke up, tossed aside at the beach near what would become the city of Cademia."*"Or so goes the legend.  I am not a @historian - perhaps you should ask another..."`,
    `"We're not from here, dude, but from the same Earth you are. We lived on this island called Thera, till Enesidaone, like, reclaimed it."*"Not without warning, though - this stranger shaped like the Holy Bull rocked up and told us to bail.  We watched Thera get wiped out from our boats, way out past the break."*"That night the most gnarly storm ever tossed us around, till in the morning we woke up washed up on the beach near what'd become Cademia.  Epic wipeout, man."*"Or so goes the legend.  I'm not a @historian, bro - maybe ask somebody else..."`),
  R('Rick: history, forgotten', 0x1802, `"There are days I don't remember what happened the day before, much less more ancient history."*"For some reason, though, the number 201 seems important.  If you find out why, please tell me..."`,
    `"Dude, some days I can't remember what happened yesterday, let alone, like, ancient history."*"For some reason, though, the number 201 feels important.  If you figure out why, tell me, bro..."`),
  R('Rick: history, remembered', 0x1802, `"My history, I remember a few parts.  Living with my mother, as a child in Catamarca.  When she died, I left Catamarca, to roam."*"How I survived, I don't know.  I think I was seeking out the exiled Mages, for I felt I had powers beyond those of normals, and I would learn of them."*"Instead of finding them, I wandered into a cave, but it was not a cave. I crossed a bridge of stars, and found an abandoned hall or temple of some sort."*"Who built this place, I knew not.  It was empty and abandoned, but great power called to me."*"I remember standing on the edge of the Abyss, and felt myself surrender to it, becoming one with it, with the Land."*"It was then that I became the Land King.  I know not how long I stood there - for years, it was certain.  And in the end, I had completed the bond."*"I knew then that rule of the Tyrants must be ended.  And thus I ended it - and from that came the current system of Houses and Judges."*"All that seems to be failing now - perhaps my time has ended..."`,
    `"My history?  I remember a few parts, dude.  Living with my mom as a grom in Catamarca.  When she died, I left Catamarca to, like, roam."*"How I survived, no clue, man.  I think I was looking for the exiled Mages, 'cause I felt like I had powers way beyond the normals, and I wanted to learn about 'em."*"Instead I wandered into a cave, but it wasn't a cave. I crossed this bridge of stars, bro, and found an abandoned hall or temple or something."*"Who built it, no idea.  It was empty and abandoned, but this great power was, like, calling to me."*"I remember standing on the edge of the Abyss, and I just let go, dude - surrendered to it, became one with it, with the Land.  Most epic drop-in ever."*"That's when I became the Land King.  Don't know how long I stood there - years, for sure.  And in the end, the bond was, like, complete."*"I knew then the Tyrants had to go.  So I ended 'em - and out of that came the whole Houses and Judges scene."*"And now it all seems to be failing - maybe my session's over, man..."`),
  R('Rick: 201', 0x1802, `"Yes, that is the day my mother passed away."`, `"Yeah, dude.  That's the day my mom passed away."`),
  R('Rick: 201 unknown', 0x1802, `"That number seems important to me, but I don't know why."`, `"That number feels important, bro, but I got no idea why."`),
  R('Rick: metics', 0x1802, `"Metics are those who lived in Cythera before we arrived.  Their ruins can be found outside Pnyx, and I hear more have been discovered in the Swamp of Khalkis"*"You should seek out a Freemage named Timon - he has studied them."`,
    `"Metics are the dudes who lived in Cythera before we showed up.  Their ruins are outside Pnyx, and I hear more got found in the Swamp of Khalkis"*"Go find a Freemage named Timon, bro - he's totally studied 'em."`),
  R('Rick: Enesidaone', 0x1802, `"Enesidaone, Mater Theia, the old gods.  They no longer guide our fate. Sadly, I'm the closest thing to a deity now..."`, `"Enesidaone, Mater Theia, the old gods, man.  They don't steer our fate anymore. Bummer is, I'm the closest thing to a deity now, dude..."`),
  R('Rick: Chrysothemis', 0x1802, `"Chrysothemis was my mother - her I remember well."`, `"Chrysothemis was my mom, dude - her I remember for sure."`),
  R('Rick: mother remembered', 0x1802, `"Yes, she was my mother - I remember now.  It was in 201 that she passed away.  Yes, that was the start of it."*"I can remember parts of my @history again.  Who knows for how long, though..."*`,
    `"Yeah, she was my mom - I remember now, dude.  It was in 201 that she passed away.  Yeah, that's where it all started."*"I can remember parts of my @history again.  Who knows for how long, though, man..."*`),
  R('Rick: mother missing', 0x1802, `"My mother, I remember, but not quite - a part of my memory is missing there..."`, `"My mom, I remember, but not quite, bro - a chunk of my memory's, like, gone there..."`),
  R('Rick: mother well', 0x1802, `"Chrysothemis was my mother - her I remember quite well now."`, `"Chrysothemis was my mom - her I remember totally clearly now, dude."`),
  R('Rick: father', 0x1802, `"Of my father, I remember nothing - perhaps I once did, but not now..."`, `"My dad?  Nothing, man - maybe I did once, but not now..."`),
  R('Rick: Piemag', 0x1802, `"Magpie might be my fool, but he is a trusted advisor."`, `"Piemag might be my fool, dude, but he's a totally trusted advisor.  Weird syntax, though."`),
  R('Rick: excuse me', 0x1802, `"Excuse me?"`, `"Uh, come again, dude?"`),
  R('Rick: stares', 0x1802, `He just stares off into space.\n`, `He just stares off at the horizon, like he's checking the swell.\n`),
  // after the "one with the land again" line above, so the fragment is the only match left
  R('Rick: thanks to you', 0x1802, ` thanks to you."`, ` thanks to you, bro."`),
  R('Rick: the good ending', 0x1802, `"You've done it!  It is remarkable - amazing.  I feel, I lack words for it."*"It is as if a fog has lifted, as if I have gained sight.  Every blade of grass, I sense."*"The land has suffered, but you have helped to cure it, and with it, me."*"I shall keep this artifact safe - its powers have re-tuned my senses."*"I don't know how to repay you for the service you've done, not only for myself, but the land as well."*"I shall return you to your own land, as I promised.  Thank you again."*Alaric waves his hands before you, and your vision grows dark...*`,
    `"Dude, you did it!  It's remarkable - amazing.  I'm, like, totally out of words, man."*"It's like a fog just lifted, like I can see again.  Every blade of grass, I feel it, bro."*"The land's been hurting, but you helped cure it, and me with it.  So stoked."*"I'll keep this artifact safe - its powers have, like, re-tuned my senses.  Radical."*"I don't know how to repay you, dude, not just for me, but for the whole land."*"I'll send you back to your own land, like I promised.  Thanks again, bro.  Catch you on the flip side."*Rick throws a shaka, waves his hands before you, and your vision grows dark...*`),
];

// ---- Piemag (Magpie), 0x1803 -----------------------------------------------
const PIEMAG = [
  R('Piemag: on the throne', 0x1803, `You see a hunchback dressed in motley, sitting on the throne.\n*"Magpie is just keeping Alaric's chair warm - is all."`, `You see a hunchback dressed in motley, sitting on the throne.\n*"Warm, Rick's chair, Piemag is only keeping.  Yes.  That is all, hmm."`),
  R('Piemag: standing', 0x1803, `You see a hunchback dressed in motley, with a pleasant demeanor.\n`, `You see a small hunchback dressed in motley, with a pleasant demeanor and very large ears.\n`),
  R('Piemag: master first', 0x1803, `"Please, talk to the master first."`, `"Talk to the master first, you must.  Hmm.  Yes."`),
  R('Piemag: names', 0x1803, `"Many names Magpie has."`, `"Many names, Piemag has.  Hmm, yes.  Many."`),
  R('Piemag: fool', 0x1803, `"Magpie is the King's Fool! Is that not enough?"`, `"The King's Fool, Piemag is!  Enough, is that not?  Hmm?"`),
  R('Piemag: place', 0x1803, `"Sorry, but Magpie's place is with Alaric."`, `"Sorry, Piemag is.  With Rick, Piemag's place is.  Go, Piemag cannot."`),
  R('Piemag: story untold', 0x1803, `"A story that can not be told, it is."`, `"A story that told cannot be, it is.  Hmm.  No."`),
  R('Piemag: history', 0x1803, `"History is everywhere, but nobody asks a rock its history."*"The history of Magpie, now there's a @story, but the history of Alaric, now that's a @tale."`, `"Everywhere, history is.  But a rock its history, nobody asks, hmm."*"The history of Piemag, a @story that is.  But the history of Rick, a @tale that is.  Yes."`),
  R('Piemag: the tale', 0x1803, `"The tale of Alaric?  His story is history!"*Alaric laughs and capers as if he has told the best joke ever invented.*"Alaric it was that destroyed the rule of the Tyrants, and brought the Mages back from exile."*"He it was that set up government as it stands today.  But none know how he gained the power to do this feat."*"Or at least, none will say.  None is no one.  And no one is not one.  And not one is two."*Alaric again beams with delight.`,
    `"The tale of Rick?  History, his story is!  Ho ho ho."*Piemag laughs and capers as if the best joke ever invented, he has told.*"Rick it was that the rule of the Tyrants destroyed, and the Mages from exile brought back."*"He it was that government set up, as today it stands.  But how the power for this feat he gained, none know."*"Or at least, say it none will.  No one, none is.  And not one, no one is.  And two, not one is.  Hmm."*Piemag again with delight beams.`),
  R('Piemag: more stories', 0x1803, `"Perhaps we will share more stories..."`, `"More stories, perhaps, share we will..."`),
  R('Piemag: the bond', 0x1803, `"A magical bond Alaric has with the land, which allows him to ensure its prosperity.  That is why he is called the Land King"*"And this place is thus Land King Hall, Hall of the Land King, Hall of Alaric."*"In truth, he is surely the King of more than just the Land."`,
    `"A magical bond with the land, Rick has, which its prosperity ensure lets him.  The Land King, that is why called he is"*"And Land King Hall, this place thus is.  Hall of the Land King.  Hall of Rick.  Hmm."*"In truth, King of more than just the Land, surely he is."`),
  R('Piemag: not welcomed', 0x1803, `"That is not a place where Magpie is welcomed."`, `"A place where welcomed Piemag is, that is not."`),
  R('Piemag: welcomed', 0x1803, `"Magpie is welcomed there, or at least was."`, `"Welcomed there, Piemag is.  Or at least, was.  Hmm."`),
  R('Piemag: wizards', 0x1803, `"City of Wizards.  They know how to treat Magpie."`, `"City of Wizards.  How to treat Piemag, they know.  Yes."`),
  R('Piemag: metics', 0x1803, `"Metics are a legend, but so is Magpie, and both are true."*"Knows them, Magpie does.  Welcome by them, Magpie is not."`, `"A legend, Metics are.  But so is Piemag.  And true, both are."*"Knows them, Piemag does.  Welcome by them, Piemag is not.  No."`),
  R('Piemag: seldane', 0x1803, `"Seldane, Seldine, are they not all the same?  Metics by any other name."`, `"Seldane, Seldine - all the same, are they not?  Metics by any other name, they are.  Hmm."`),
  R('Piemag: a son', 0x1803, `"A son Magpie has, and met him you have.  @Three that are one, he is.`, `"A son, Piemag has, and met him, you have.  @Three that are one, he is.`),
  R('Piemag: no more', 0x1803, `  More Magpie can not say.`, `  More, say Piemag cannot.  No.`),   // the closing quote after it is a jump target and stays
  R('Piemag: one', 0x1803, `"It is easy to say that one is, or is it?  Can one truly say what one is, and what one isn't?"*"Is one really one, or perhaps two?  Mayhaps even three?"`, `"Easy to say that one is, it is.  Or is it?  Truly say what one is, and what one isn't, can one?"*"Really one, is one?  Or perhaps two?  Mayhaps even three, hmm?"`),
  R('Piemag: two', 0x1803, `"Two matters not, but three?"`, `"Matter not, two does.  But three?  Hmm."`),
  R('Piemag: four', 0x1803, `"Could there be four?  Why with man there can be five!"`, `"Four, could there be?  Why, with man, five there can be!  Ho ho."`),
  R('Piemag: five', 0x1803, `"If two of five are lost, there are then but three."`, `"Lost, two of five are?  Then but three, there are.  Yes."`),
  R('Piemag: three', 0x1803, `"Jhiaxus is one.  Jinrai is one."*"Bahoudin is two.  Chrysothemis is one."*"Alaric is three."`, `"One, Jhiaxus is.  One, Jinrai is."*"Two, Bahoudin is.  One, Chrysothemis is."*"Three, Rick is.  Hmm."`),
  R('Piemag: not ready', 0x1803, `"Ah, three, now that is important, but you are not ready for that knowledge."`, `"Ah, three.  Important, that is.  But ready for that knowledge, you are not.  Patience."`),
  R('Piemag: mother', 0x1803, `"Mother of Alaric is that one."`, `"Mother of Rick, that one is."`),
  R('Piemag: the name', 0x1803, `"You know the name - a dangerous tool it is, but a tool nonetheless."*"A tool to open, a tool to close."*"A tool to build, a tool to destroy."*"A tool to heal, a tool to poison."`, `"Know the name, you do.  A dangerous tool, it is.  But a tool nonetheless, hmm."*"A tool to open, a tool to close."*"A tool to build, a tool to destroy."*"A tool to heal, a tool to poison.  Yes."`),
  R('Piemag: Sabinate', 0x1803, `*"Sabinate is right perhaps, but one can be wrong when one is right."*"Magpie fears it is last best hope for Alaric - great is the risk."`, `*"Right, Sabinate is, perhaps.  But wrong when right, one can be."*"Fears, Piemag does, that the last best hope for Rick it is.  Great, the risk is.  Hmm."`),
  R('Piemag: visions', 0x1803, `"Not all visions see deep to the truth of what is, and what must never be."`, `"Deep to the truth of what is, and what must never be, not all visions see.  No."`),
  R('Piemag: old name', 0x1803, `"An old name, not used anymore."`, `"An old name, that is.  Used anymore, it is not."`),
  R('Piemag: motives', 0x1803, `"Many people have many motives, not all bode well."`, `"Many motives, many people have.  Bode well, not all do."`),
  R('Piemag: Jinrai', 0x1803, `"People of Jinrai are dangerous - very much so."`, `"Dangerous, the people of Jinrai are.  Very much so, yes."`),
  R('Piemag: the dead', 0x1803, `*"Remember well that the dead do not walk."`, `*"Remember well, you must: walk, the dead do not."`),
  R('Piemag: glances at Rick', 0x1803, `He glances briefly at Alaric, as if to see if he is listening.*"That is a story that is not for Magpie to tell."`, `He glances briefly at Rick, as if to see if listening he is.*"A story that for Piemag to tell is not, that is."`),
  R('Piemag: not safe', 0x1803, `"Please - that name is not safe.  Magpie never uses that name."`, `"Please - safe, that name is not.  Never uses that name, Piemag does."`),
  R('Piemag: Bahoudin', 0x1803, `He glances around briefly.*"Magpie and Bahoudin, many stories.  That story is true."*`, `He glances around briefly.*"Piemag and Bahoudin, many stories there are.  True, that story is.  Hmm."*`),
  R('Piemag: the key', 0x1803, `"Yes, truth speaks Jhiaxus.  Magpie shall yield it to you, but there is great danger."*`, `"Yes, truth Jhiaxus speaks.  Yield it to you, Piemag shall.  But great danger, there is."*`),
  R('Piemag: fears', 0x1803, `"Great danger for all.  Magpie's fears come true..."*"You shall save us all..."*"...or destroy us all."*"You alone have the power to make the choice."*"Magpie sees better than Sabinate or Jhiaxus, but this is unseen."*"Sabinate and Jhiaxus have their own motives - remember this."*`,
    `"Great danger, for all.  True, Piemag's fears come..."*"Save us all, you shall..."*"...or destroy us all."*"The power to choose, you alone have."*"Better than Sabinate or Jhiaxus, Piemag sees.  But unseen, this is.  Clouded, the future is."*"Their own motives, Sabinate and Jhiaxus have.  Remember this, you must."*`),
  T('Piemag: not to tell, three times', 0x1803, `"That is a story that is not for Magpie to tell."`, `"For Piemag to tell, that story is not.  Hmm."`, 3),   // after the glance line took the fourth
  R('Piemag: the king', 0x1803, `"The Kind is Alaric and Alaric is the King, @bonded to the @land."`, `"The King, Rick is, and Rick, the King is.  @Bonded to the @land, he is.  Yes."`),
  R('Piemag: land and water', 0x1803, `"Land and water, water and land - those two are not one, except for two, who are two and three."`, `"Land and water, water and land - one, those two are not.  Except for two, who two and three are.  Confusing, this is.  Hmm."`),
  R('Piemag: Ignae', 0x1803, `"Old Ignae is a trickster - the sly one he is."`, `"A trickster, old Ignae is.  The sly one, he is.  Yes."`),
  R('Piemag: tourguide', 0x1803, `"Tourguide Magpie has played for you once."`, `"Tourguide, Piemag has played for you once.  Twice, Piemag will not.  Hmm."`),
];

// ---- RAMBO (Hadrian), 0x1804 -----------------------------------------------
const RAMBO = [
  R('RAMBO: description', 0x1804, `You see an older warrior, with a proud demeanor.*`, `You see an older warrior with a red bandanna, a thousand-yard stare, and a knife the size of your forearm.*`),
  R('RAMBO: greeting', 0x1804, `"Greetings, and welcome to our world, stranger.  I am Hadrian, the Captain of Alaric's Guard, and @Trainer."`, `"They drew first blood, not me.  Name's RAMBO.  Captain of Rick's Guard.  @Trainer.  Welcome to our world, stranger.  Don't push it."`),
  R('RAMBO: again', 0x1804, `"Greetings again, stranger`, `"You again, stranger.  Nothing is over`),
  R('RAMBO: name', 0x1804, `"I am called Hadrian, the Captain of Alaric's Guards."`, `"RAMBO.  Captain of Rick's Guards.  That's all you need to know."`),
  R('RAMBO: job', 0x1804, `"I am in charge of the guards that protect Alaric and Land King Hall."`, `"I run the guards that protect Rick and Land King Hall.  To survive a war, you gotta become war."`),
  R('RAMBO: proud', 0x1804, `"I am proud of the service that Hector has done for you."`, `"Hecky's done his service.  I'm proud.  I don't say that twice."`),
  R('RAMBO: served with honor', 0x1804, `"He has served you with honor, hasn't he!  I'm quite proud of him."*`, `"He served you with honor.  Didn't he.  Good.  In here he's still a boy - out there, he's a soldier."*`),
  R('RAMBO: Hecky blushes', 0x1804, `Hector blushes...*`, `Hecky blushes and hugs RAMBO's leg...*`),
  R('RAMBO: how is my son', 0x1804, `"How's my son doing?  Is he serving you with honor?"*`, `"My boy.  How's he doing.  He serving you with honor?"*`),
  R('RAMBO: indeed', 0x1804, `"Indeed I am."`, `"I am.  Live for nothing, or die for something."`),
  R('RAMBO: died', 0x1804, `"I regret to tell you that Hector has died in my service.  I am truly sorry."*`, `"Hecky's dead.  He died in my service.  I'm sorry.  I truly am."*`),
  R('RAMBO: choked up', 0x1804, `Hadrian seems choked up, and unable to speak for a moment.\n*"Thank you for telling me.  We all knew the risks involved."*"A warrior can know no better death than to die for a cause that is right and just."*`,
    `RAMBO stares at the wall.  His jaw works.  Nothing comes out for a long moment.\n*"Thanks for telling me.  We all knew the risks.  Back home, nobody knows."*"A warrior can know no better death than dying for a cause that's right and just.  When you're pushed, killing's as easy as breathing."*`),
  R('RAMBO: fine son', 0x1804, `"Hector is a fine son, and will serve you with honor."`, `"Hecky's a fine son.  He'll serve you with honor.  Or he'll answer to me."`),
  R('RAMBO: fine lad', 0x1804, `"My son Hector is fine lad - he will be a great warrior and leader, once he has a bit more experience."`, `"My boy Hecky's a fine lad.  He'll be a great warrior and leader, once he's seen some action.  Right now he mostly sees me."`),
  R('RAMBO: permission given', 0x1804, `"Why, nothing would make me more proud!  He will serve you with honor!"*`, `"Take him.  Nothing'd make me prouder.  He'll serve you with honor.  Bring him back or don't come back."*`),
  R('RAMBO: train', 0x1804, `"I can @train you in that, if you'd like."`, `"I can @train you in that.  It won't be pretty.  Your choice."`),
  R('RAMBO: Eioneus', 0x1804, `"I remember him - a bright young mage who was working on magically enhancing weapons."*"I haven't seen him for years now, I wonder how he's doing...  He might be worth tracking down."*`, `"I remember him.  Bright young mage.  Magically enhanced weapons.  My kind of research."*"Haven't seen him in years.  Might be worth tracking down.  I'm good at tracking."*`),
  R('RAMBO: farewell thanks', 0x1804, `"Farewell, and thank you."`, `"Move out.  And... thanks."`),
  R('RAMBO: farewell', 0x1804, `"Farewell."`, `"Move out."`),
  R('RAMBO: a favor', 0x1804, `*"Actually, if you don't mind, I was wondering if you could do a favor for me?"*"My mother passed away recently, but with my duties here, I don't have time to properly honor her."*"Could you place these flowers on her grave?  She is buried in the graveyard in Catamarca..."`,
    `*"Wait.  One thing.  A favor.  I don't ask favors."*"My mother died recently.  With my duties here I can't honor her the way she deserves."*"Put these flowers on her grave.  Graveyard in Catamarca.  Don't make me ask twice..."`),
  R('RAMBO: Andra', 0x1804, `"Thank you.  Her name was Andra, and she is buried next to my father Lycus"`, `"Good.  Her name was Andra.  She's buried next to my father Lycus.  Now get out of here"`),
  R('RAMBO: declined', 0x1804, `"Well, I understand.  Thank you for considering it anyway."`, `"Understood.  Forget I asked.  Nothing is over."`),
  R('RAMBO: mother', 0x1804, `"Andra was my mother."`, `"Andra.  My mother.  Don't."`),
  R('RAMBO: father', 0x1804, `"Lycus was my father."`, `"Lycus.  My father.  He taught me everything."`),
  R('RAMBO: no help', 0x1804, `"Can't help you on that."`, `"Can't help you there.  Ask someone who talks."`),
];

// ---- Emetic (Emesa), 0x1805 ------------------------------------------------
const EMETIC = [
  R('Emetic: description', 0x1805, `You see an older woman, a bit weary but happy.*`, `You see an older woman, floury to the elbows, with the thousand-yard stare of someone asked for flatbread one too many times.*`),
  R('Emetic: greeting', 0x1805, `"Greetings, and welcome to our world, stranger.  I am Emesa, Alaric's @cook."*"If there's @anything I can do for you to help you in your @journeys, please, just ask..."`, `"Greetings, stranger, welcome to our world.  I am Emetic, Rick's @cook.  And no, before you ask - no flatbread."*"If there's @anything I can do for you in your @journeys, anything at all that is not flatbread, please, just ask..."`),
  R('Emetic: again', 0x1805, `"Greetings again, stranger.`, `"Greetings again, stranger.  Don't say it.`),
  R('Emetic: name', 0x1805, `"I am Emesa, `, `"I am Emetic, `),
  R('Emetic: cook', 0x1805, `"I am the @cook for @Alaric - my specialty is bread."`, `"I am the @cook for @Rick - my specialty is bread.  Real bread.  Not flatbread.  Everyone wants flatbread.  I loathe flatbread."`),
  R('Emetic: husband', 0x1805, `"Yes, my husband is Hadrian, the captain of the guards here..."*"A loving father, and a strong man, although a Alaric's ailing health has him troubled."*"You'll find him at the Land King's side most of the time these days...."`,
    `"Yes, my husband is RAMBO, captain of the guards here...  He shouts his own name a lot."*"A loving father, and a strong man, although Rick's ailing health has him troubled, and he only eats his flatbread cold, out of a tin."*"You'll find him at the Land King's side most of the time these days, sharpening things...."`),
  R('Emetic: beloved', 0x1805, `"Yes, Hadrian is my beloved husband..."*"He works so hard to protect and care for Alaric in these times of strife, I @worry about him..."`, `"Yes, RAMBO is my beloved husband..."*"He works so hard to protect and care for Rick in these times of strife, I @worry about him...  He hasn't taken the bandanna off since spring."`),
  R('Emetic: worry', 0x1805, `"He rarely sleeps, and has become quite withdrawn of late..."*"I think his @concern for Alaric is overpowering the man I love; it's quite a burden for him to bear."*"You see, Hadrian's sworn duty is to protect Alaric, and Land King Hall, but now that an unseen force has afflicted his liege, he is left powerless to do anything about it."`,
    `"He rarely sleeps, and has become quite withdrawn of late..."*"I think his @concern for Rick is overpowering the man I love; it's quite a burden for him to bear, and he takes it out on the woodpile."*"You see, RAMBO's sworn duty is to protect Rick, and Land King Hall, but now that an unseen force has afflicted his liege, he is left powerless to stab anything about it."`),
  R('Emetic: concern', 0x1805, `"Hadrian's concern for Alaric has in turn led to my concern for my husband."*"He hasn't even had time to properly @mourn the passing of his mother, let alone tend to his family that still lives."`, `"RAMBO's concern for Rick has in turn led to my concern for my husband."*"He hasn't even had time to properly @mourn the passing of his mother, let alone tend to his family that still lives - and the family would like some proper bread, thank you."`),
  R('Emetic: mourn', 0x1805, `"Hadrian's kindly mother passed away recently in Catamarca."*"She was such a kindly old woman, but one with much life left within her."*"A terrible shame to have it stolen from her."`, `"RAMBO's kindly mother passed away recently in Catamarca."*"She was such a kindly old woman, but one with much life left within her.  She never once asked me for flatbread."*"A terrible shame to have it stolen from her."`),
  R('Emetic: concerned for Rick', 0x1805, `"I too am concerned for Alaric..."*"I do what I can providing him with nourishing food to ease his weary bones and troubled brow."*"These are troubled times, stranger.  I do hope you can help him, and by doing so, help us, and all of the land of Cythera."`, `"I too am concerned for Rick..."*"I do what I can, providing him with nourishing food to ease his weary bones and troubled brow.  He asks for flatbread.  He gets soup."*"These are troubled times, stranger.  I do hope you can help him, and by doing so, help us, and all of the land of Cythera, and its dreadful flatbread habit."`),
  R('Emetic: son', 0x1805, `"Hector is our son - we are very proud of him."`, `"Hecky is our son - we are very proud of him.  He's a little young for his age.  He still calls his father Daddy.  Loudly."`),
  R('Emetic: ask RAMBO', 0x1805, `"You'll have to talk to Hadrian about that."`, `"You'll have to talk to RAMBO about that.  Speak slowly, and don't stand too close."`),
  R('Emetic: honor to cook', 0x1805, `"It is an honor to cook @food for Alaric."`, `"It is an honor to cook @food for Rick.  Real food.  With a crust.  That rises."`),
  R('Emetic: Piemag', 0x1805, `"Magpie is quite the jester, isn't he?"`, `"Piemag is quite the jester, isn't he?  Ask for flatbread, he does.  Backwards.  Every day."`),
  R('Emetic: journeys', 0x1805, `"Oh, I'd imagine you'll be traveling far and wide soon.  Be careful, keep your eyes open, and perhaps see if you can get some people to help you along the way."*"Nothing like having friends to help you out of a rough spot..."*"I don't travel much myself, so I don't know much about the goings on in the land, but my @husband is quite worldly."*"Perhaps he can tell you a thing or two?"`,
    `"Oh, I'd imagine you'll be traveling far and wide soon.  Be careful, keep your eyes open, and perhaps see if you can get some people to help you along the way."*"Nothing like having friends to help you out of a rough spot...  Friends who bring their own bread."*"I don't travel much myself, so I don't know much about the goings on in the land, but my @husband is quite worldly.  He's been to some very loud places."*"Perhaps he can tell you a thing or two?  Or grunt it?"`),
  R('Emetic: food', 0x1805, `"Well, I can offer you some @food if you like, but what we have around here won't keep you nourished for too long while off on travels..."*"Who knows how long it will be before you're able to find another place to @catch a meal?"*"You'll be able to get a something to eat at various @Inns, of course, but for a price."`,
    `"Well, I can offer you some @food if you like.  It will be flatbread.  It is always flatbread.  I make it taste like a wet sandal on purpose, and still they come..."*"Who knows how long it will be before you're able to find another place to @catch a meal?  Somewhere with proper bread, I hope, for your sake."*"You'll be able to get a something to eat at various @Inns, of course, but for a price.  Worth it.  Trust me."`),
  R('Emetic: animals', 0x1805, `"Animals roaming in the wilds of Cythera are a good source of meat, but be careful not to wantonly slaughter animals in town."*"They invariably belong to someone, and they'll be none too pleased with you."*"Please... if you do kill such wild animals for food, do so quickly and mericifully..."`,
    `"Animals roaming in the wilds of Cythera are a good source of meat, but be careful not to wantonly slaughter animals in town."*"They invariably belong to someone, and they'll be none too pleased with you."*"Please... if you do kill such wild animals for food, do so quickly and mercifully...  Meat.  Now there's a thing you can cook without anyone asking you to flatten it."`),
  R('Emetic: inns', 0x1805, `"Oh, just about every village in Cythera has an Inn... a place where you can get a hot meal, and a good night's sleep."*"I don't condone many of the sort who hang about there for the drink, however..."*"And of course, you're always welcome to come back here instead, where I can give you something to eat before you turn in at your quarters for the night."`,
    `"Oh, just about every village in Cythera has an Inn... a place where you can get a hot meal, and a good night's sleep."*"I don't condone many of the sort who hang about there for the drink, however...  Though at least the drunks don't want flatbread."*"And of course, you're always welcome to come back here instead, where I can give you something to eat before you turn in.  It will be flatbread.  It will be awful.  This is on purpose."`),
  R('Emetic: hungry?', 0x1805, `"Are you hungry, and in need of food?"`, `"Are you hungry?  Are you about to ask me for flatbread?  Are you sure?"`),
  R('Emetic: gives food', 0x1805, `"Let me get you something to eat."*She gives you some food\n`, `"Fine.  FINE.  Here."*She slaps a flatbread into your hands.  It smells faintly of resentment and old fish\n`),
  R('Emetic: ask when hungry', 0x1805, `"Well, make sure to ask me if you are hungry."`, `"Well, ask me if you are hungry.  Everyone does.  Every.  Single.  Day."`),
  R('Emetic: refresher', 0x1805, `"Need a refresher?  I can understand - you've more important things on your mind."*`, `"Need a refresher?  I can understand - you've more important things on your mind than my suffering."*`),
  R('Emetic: learn bread?', 0x1805, `"Would you like to learn how to make bread?"`, `"Would you like to learn how to make bread?  Real bread?  Or are you another flatbread person?"`),
  R('Emetic: other time', 0x1805, `"Perhaps some other time."`, `"Perhaps some other time.  When you've grown a palate."`),
  R('Emetic: recipe', 0x1805, `"Baking bread isn't that hard - Take some flour and spread it out."*"Take some water and add to the flour."*"Take a rolling pin and roll out the dough."*"Take the finished dough and bake it, and you're done!"`, `"Baking bread isn't that hard - Take some flour and spread it out."*"Take some water and add to the flour."*"Take a rolling pin and roll out the dough.  Not too flat.  Never too flat.  Do you hear me?"*"Take the finished dough and bake it, and you're done!  If it comes out flat, it's your own fault, and I'll know."`),
  R('Emetic: farewell', 0x1805, `"Farewell."`, `"Farewell.  Eat something decent."`),
  R('Emetic: not familiar', 0x1805, `"I'm sorry, but I'm not familiar with that."`, `"I'm sorry, but I'm not familiar with that.  Unless it's a kind of flatbread, in which case I refuse to be."`),
];

// ---- Hecky (Hector), 0x1806 ------------------------------------------------
const HECKY = [
  R('Hecky: weapon', 0x1806, `"It'll work as a weapon, but I've only been trained in edged weapons..."`, `"It'll work as a weapon, but Daddy only teached me the pointy ones..."`),
  R('Hecky: description', 0x1806, `You see a young warrior, with a look of fire in his eyes.*`, `You see a young warrior with a look of fire in his eyes, a thumb in his mouth, and a wooden sword that says DADDY on it.*`),
  R('Hecky: greeting', 0x1806, `"Ah, you are the one that was summoned by Alaric - my name is Hector, and I am honored to meet you!"`, `"Ooh!  You're the one Rick summoned!  My name is Hecky, and I'm honored to meet you!  Have you met my DADDY?  He's the bestest."`),
  R('Hecky: my leader', 0x1806, `"Yes, my leader, what can I do for you?"`, `"Yes, my leader!  What can I do?  Is it something Daddy would do?"`),
  R('Hecky: service', 0x1806, `, how can I be of service?"`, `, how can I be of service?  Daddy says I'm very helpful."`),
  R('Hecky: earthquake', 0x1806, `"This is our training room, but with the damage done by that @earthquake, I don't know"`, `"This is our training room, where Daddy trains me!  But with the damage from that @earthquake, I dunno"`),
  R('Hecky: tremors', 0x1806, `"This area has always had minor tremors, but this is the first one that caused major damage."*"Come to think of it, there have been more tremors here since Alaric began to weaken."`, `"This area always had little wobbles, but this is the first one that broke stuff.  I hid behind Daddy."*"Come to think of it, there's been more wobbles here since Rick started getting poorly."`),
  R('Hecky: name', 0x1806, `"I am called Hector - our legends tell of a great @warrior named Hector, and I hope to follow in his, and my @father's footsteps."*"So you're the @stranger that Alaric has summoned here to aid him?"`, `"I'm Hecky!  Our legends tell of a great @warrior called Hector, but mostly I want to be like my @father, 'cause he's my DADDY and he's the strongest."*"So you're the @stranger Rick summoned here to help him?  Does Daddy know?"`),
  R('Hecky: job', 0x1806, `"I am a warrior, or at least will be one, like my father."`, `"I'm a warrior!  Or I will be, like Daddy.  Daddy's a warrior.  Did you know Daddy's a warrior?"`),
  R('Hecky: father', 0x1806, `"My father Hadrian is the head of Alaric's guards - it is a very honorable profession"`, `"My daddy is RAMBO, and he's the head of Rick's guards, and it's very honorable, and he can lift a whole horse, probably"`),
  R('Hecky: stranger', 0x1806, `"Well, I hope Alaric knows what he's doing.  No offense, but you don't look like much of a hero to me..."*"However I suppose looks can be deceiving, as my @mother always says"`, `"Well, I hope Rick knows what he's doing.  No offense, but you don't look like much of a hero to me...  Not like Daddy."*"But looks can be deceiving, my @mother always says, mostly about Daddy's flatbread face"`),
  R('Hecky: mother', 0x1806, `"My mother's right around the corner in the kitchen, usually."*"She's a kind-hearted soul, and it kills me to see her working at such a menial job."*"She's here mostly to be close to my @father, I think, and she does seem to enjoy her @work."`, `"Mommy's right around the corner in the kitchen, usually.  Don't ask her for flatbread.  She gets scary."*"She's a kind-hearted soul, and it makes me sad to see her working so hard."*"She's here mostly to be close to my @father, I think, 'cause everybody wants to be close to Daddy, and she does seem to like her @work."`),
  R('Hecky: work', 0x1806, `"Well, she prepares all of the meals for folks in the Land King Hall, including @Alaric himself!"*"Say, I bet if you asked her, she'd be more than willing to cook you a hot meal..."`, `"Well, she makes all the meals for everybody in Land King Hall, even @Rick himself!  And Daddy!  Daddy eats the most."*"Say, I bet if you asked her, she'd cook you a hot meal...  Just don't say the F-word.  Flatbread.  Oops."`),
  R('Hecky: Rick', 0x1806, `"Alaric is more than just our ruler, he binds the land together in some strange way that I don't understand."*"I may not know exactly what is going on, but I do know that as Alaric has weakened, the land has @suffered as well."`, `"Rick is more than just our ruler, he glues the land together somehow, in a way I don't get.  Daddy probably gets it."*"I dunno exactly what's going on, but I do know that as Rick got poorly, the land got @suffered too."`),
  R('Hecky: suffered', 0x1806, `"Much has happened in Cythera that would be unthinkable just a few scant years ago..."*"It's as if the land is stricken with a disease, and can no longer fight back against agents of @evil,"`, `"Lots has happened in Cythera that would've been unthinkable a few years ago...  I was even littler then."*"It's like the land has a tummy bug, and can't fight back against agents of @evil,"`),
  R('Hecky: criminals', 0x1806, `"I've heard stories of @criminals roaming rapant, and stranger still, of odd creatures roaming about."`, `"I've heard stories of @criminals roaming rapant, and stranger still, of odd creatures roaming about.  Daddy would biff them all."`),
  R('Hecky: cowards', 0x1806, `"How I'd love to give them a taste of their own medicine!  Dark-hearted cowards!"*"Cythera should return to the just land it once was..."`, `"I'd love to give them a taste of their own medicine!  Dark-hearted meanies!  Daddy says they drew first blood."*"Cythera should go back to being the nice land it was..."`),
  R('Hecky: warrior', 0x1806, `"Yes, I hope to honor my @father, and as well as make a name for myself."*"I've been @training and studying the ways of a warrior."`, `"Yes, I want to make Daddy proud of me, my @father, and maybe make a name for myself too, but mostly Daddy."*"I've been @training and studying the ways of a warrior.  Daddy's ways.  Daddy has all the ways."`),
  R('Hecky: training', 0x1806, `"My father helped me out with that; he's a great warrior in his own right, as well as a patient teacher."*"I think I've passed the point where training alone can help me, however..."`, `"Daddy helped me with that; he's a great warrior and a patient teacher and he gives the best piggybacks."*"I think I've got past the point where training alone can help me, though...  Daddy says I need to see the elephant.  I don't know what that means."`),
  R('Hecky: honor', 0x1806, `"Without honor, there is no meaning to life.  Most citizens of Cythera value honor highly, but myself more so than most."`, `"Without honor there's no meaning to life.  Daddy said that.  Most people in Cythera like honor a lot, but me more than most, 'cause Daddy."`),
  R('Hecky: already following', 0x1806, `"But I'm already following you..."`, `"But I'm already following you...  Like I follow Daddy."`),
  R('Hecky: ask father', 0x1806, `"I would be honored, but I have my duty to my @father - you'll need to ask him first."`, `"I'd be honored!  But I gotta do what my @father says - you'll need to ask Daddy first.  Ask nicely."`),
  R('RAMBO: permission', 0x1806, `*"Don't be silly - it would honor me if you would allow my son to serve you in your quest!"*`, `*"Take the boy.  It'd honor me.  He's ready.  He's been ready since he was four."*`),
  R('Hecky: thank you father', 0x1806, `"Thank you very much, Father.  I will do you proud."*`, `"Thank you, Daddy!  Thank you thank you thank you!  I'll make you so proud!"*`),
  R('Hecky: father said yes', 0x1806, `"My father said yes?  That is wonderful.  I am honored to join you on your most noble quest."`, `"Daddy said yes?  DADDY SAID YES!  I'm honored to join you on your most noble quest!  Can we tell Daddy about it after?"`),
  R('Hecky: rejoin', 0x1806, `"It would be the highest honor to re-accompany you!"`, `"It'd be the highest honor to come along again!  Daddy will be so pleased!"`),
  R('Hecky: served poorly?', 0x1806, `"Have I served you poorly?"`, `"Did I do a bad?  Are you gonna tell Daddy?"`),
  R('Hecky: woe', 0x1806, `"Woe is me!  If you would give me another chance, I'll prove myself."`, `"Waaah!  Please please give me another chance, I'll prove myself, please don't tell Daddy!"`),
  R('Hecky: very well', 0x1806, `"Very well, you have your own destiny to follow - please seek me out if you ever need a companion."`, `"Okay.  You have your own destiny to follow - come find me if you ever need a companion.  I'll be with Daddy."`),
  T('Hecky: not in party, twice', 0x1806, `"I'm not currently in the party.  Perhaps I should @join you."`, `"I'm not in the party right now.  Maybe I should @join you!  Daddy would want me to."`, 2),
  R('Hecky: wait', 0x1806, `"I shall wait here until your return."`, `"I'll wait right here till you come back.  I won't move.  Daddy taught me."`),
  R('Hecky: gladly', 0x1806, `"Gladly."`, `"Yay!"`),
  R('Hecky: not waiting', 0x1806, `"I'm not currently waiting to rejoin you.  Perhaps I should @join you."`, `"I'm not waiting to rejoin you right now.  Maybe I should @join you!"`),
  R('Hecky: anything else', 0x1806, `"Let me know if there is anything else I can do for you..."`, `"Let me know if there's anything else I can do...  I can do lots.  Daddy showed me."`),
  R('Hecky: until we meet', 0x1806, `"Until we meet again..."`, `"Bye-bye!  Till we meet again!  I'm gonna go find Daddy!"`),
  R('Hecky: confused', 0x1806, `"You confuse me with your words."`, `"You confuse me with your words.  Daddy doesn't use words much."`),
];

// ---- LKH Bro (the guard), 0x1807 --------------------------------------------
const BRO = [
  R('Bro: description', 0x1807, `You see a very serious-looking guard.*`, `You see an extremely jacked guard, flexing at nothing in particular.*`),
  R('Bro: job', 0x1807, `"I guard Alaric here in Land King Hall."`, `"I guard Rick here in Land King Hall, bro.  Guarding's basically cardio.  You lift?"`),
  R('Bro: goodbye', 0x1807, `"Goodbye, stranger."`, `"Later, bro.  Never skip leg day."`),
  R('Bro: not permitted', 0x1807, `"I am just a guard, and not permitted to talk of such."`, `"Bro, I'm just a guard, I'm not allowed to talk about that.  Gains, though?  I can talk gains all day, bro."`),
];

// ---- Ollum (Omen), in the hero's script 0x1801 ----------------------------
const OLLUM = [
  R('the hero dies', 0x1801, `You die, not knowing the fate of Alaric.`, `You die, not knowing the fate of Rick.`),
  R('Ollum: first vision', 0x1801, `A strange-looking face suddenly fades into view before you...*"Poor little human - so far from home, and so far from the truth..."*"You do know, don't you, that Alaric is not all he says he is.  True, he is bound to the land, but as a usurper."*"He does not belong in the position of power, and he upsets the balance of the world by being there."*"And you, my friend, are just another puppet of his.  Now is the time of change, and you are at the pivot point."*"But which way will the balance swing?  To the East? Or to the West?"*"And myself?  I am Omen, and my master has instructed me to watch for one like you."*`,
    `A strange-looking face suddenly fades into view before you, all eyes and teeth...*"Poor little human, yesss - so far from home, and so far from the truth, precious..."*"It knows, doesn't it, gollum, that Rick is not all he says he is.  True, he is bound to the land, yesss, but as a usurper, a thief, a nasty thief."*"He doesn't belong in the big chair, no, and he upsets the balance of the whole world by sitting in it, precious."*"And you, my friend, my precious friend, are just another puppet of his.  Now is the time of change, yesss, and you are at the pivot point.  We sees it."*"But which way will the balance swing?  To the East?  Or to the West?  Gollum, gollum."*"And us?  We are Ollum, precious, and our master told us to watch for one like you.  Nice and juicy, sss."*`),
  R('Ollum: second vision', 0x1801, `"At great price to myself I come to you, as a vision, to warn and guide you, protect and teach you."*"Know you this - there is more going on here than meets the eye, a power struggle as old as the world itself."*"And in this struggle, you are trapped.  If you ever expect to be free, heed my advice well."*"Alaric must be destroyed to restore the land, and in the end, you will do this."*"To aid you in your destiny, we have a small gift, to prove our word."*"But first, you must learn the ways of the land, and to this end my master has prepared a small test of your abilities."*"For you must hone your skills.  As a sword is tempered, so must you be."*"Seek your way out of this proving grounds, and along the way you might find your reward."*"Follow our counsel, and you will be well rewarded - ignore it at your own peril."*"Until we meet again, be on your guard, and trust not what your eyes behold."*`,
    `"It costs us, precious, it costs us so much, to come to it like this, as a vision, to warn it and guide it, protect it and teach it, yesss."*"Know this, it must - there's more going on here than meets the eyes, gollum, a power struggle as old as the world itself."*"And in this struggle it is trapped, like a fish, a wriggling fish.  If it ever wants to be free, it listens to us, precious, it listens good."*"Rick must be destroyed to fix the land, yesss, and in the end, it will do this.  It will.  We sees it."*"To help it with its destiny, we has a small gift, precious, to prove our word.  We doesn't lie.  Not to it."*"But first it must learn the ways of the land, so our master has made a little test of what it can do, gollum."*"It must sharpen itself.  As a sword is tempered, so must it be, sss."*"Find its way out of these proving grounds, and along the way it might find its reward.  Might.  If it's clever, precious."*"Follow our counsel and it will be well rewarded - ignore it and it goes in the pot, yesss."*"Until we meets again, keep its guard up, and trust not what its eyes behold.  Gollum!"*`),
  R('Ollum: first piece', 0x1801, `The vision of Omen re-appears before you...*"Excellent!  You've found the first piece of the Crolna!"*"It will be most useful, trust me.  Seek out the rest of it..."*Just as suddenly, the vision fades.*`, `The vision of Ollum re-appears before you, rubbing its hands...*"Excellent, precious, excellent!  It found the first piece of the Crolna!  Shiny piece, yesss!"*"Most useful it will be, trust us.  Seek out the rest of it, gollum, the rest, the rest..."*Just as suddenly, the vision fades.*`),
  R('Ollum: reform', 0x1801, `Again, Omen appears before your eyes...*"Ah, I see you have begun to reform the Crolna as a whole!  Excellent!"*"Now you are on to the heart of the mystery.  Once completed, the Crolna will be able to cure the land."*"Of course, you'll need the courage to wield it, but we have faith in you and your judgment."*"Beware your enemy, though, for they will ensnare you with lies hidden in half truths."*Omen fades away...*`, `Again, Ollum appears before your eyes...*"Ah, we sees it has begun to put the Crolna back together!  Excellent, precious!"*"Now it's on to the heart of the mystery, yesss.  Once it's whole, the Crolna can cure the land, gollum."*"Of course it'll need the courage to wield it, but we has faith in it, precious, and its judgment.  Mostly."*"Beware its enemy, though, sss, for they'll catch it with lies hidden in half truths.  Tricksy.  Not like us."*Ollum fades away...*`),
  R('Ollum: destiny', 0x1801, `Omen appears in a vision again...*"You have done well, and we are proud of your accomplishments.  Now is the time for you to complete your destiny."*"You know what you need to do - do not fail us!"*Omen fades away...*`, `Ollum appears in a vision again...*"It has done well, and we is proud of it, so proud, precious.  Now is the time for it to complete its destiny, gollum."*"It knows what it needs to do - it doesn't fail us!  It doesn't!  Or else, sss."*Ollum fades away...*`),
  R('Ollum: welcome', 0x1801, `The vision of Omen appears before you...*"Welcome to the wide world of Cythera!  A ready hero`, `The vision of Ollum appears before you...*"Welcome to the wide world of Cythera, precious!  A ready hero`),
  R('Ollum: unseen', 0x1801, `"Oh, by the way, don't worry, none of your fellow adventurers can see me."*"They don't even notice what's going on - they aren't quick enough to catch this instant."*`, `"Oh, by the way, don't it worry, none of its fellow adventurers can see us, gollum."*"They doesn't even notice what's going on - they isn't quick enough to catch this instant.  Slow, stupid, fat."*`),
  R('Ollum: alone', 0x1801, `"Adventuring alone can be hazardous - perhaps you should have recruited somebody from Land King Hall."*`, `"Adventuring alone can be hazardous, precious - perhaps it should have taken somebody from Land King Hall.  Somebody juicy."*`),
  R('Ollum: Hecky', 0x1801, `"Perhaps that eager young Hector might want to come along.  Might be worth asking if his father lets him grow up."*`, `"Perhaps that eager little Hecky might want to come along.  Might be worth asking, if his daddy lets him grow up, sss."*`),
  // The Hecky line above branches into the middle of this one, at "There
  // are basically two important things", so it is two edits with the
  // landing point between them.
  R('Ollum: two things, opening', 0x1801, `"Perhaps some eager young warrior living in Land King Hall might want to come along, if his father lets him grow up."*`,
    `"Perhaps some eager young warrior living in Land King Hall might want to come along, if his daddy lets him grow up, gollum."*`),
  R('Ollum: two things', 0x1801, `"There are basically two important things you need to investigate right away - a plague in Catamarca, and a kidnapping in Odemia."*"Either way, just follow the road down along the coast - Odemia is the first city you'll find, Catamarca the second."*"Good luck - and to start out, you might want to only travel during daytime, since some dangerous creatures come out at night."*"And whatever you do, stay away from the shoreline!"*`,
    `"There's basically two important things it needs to look into right away, precious - a plague in Catamarca, and a kidnapping in Odemia."*"Either way, it follows the road down along the coast - Odemia is the first city it finds, Catamarca the second, yesss."*"Good luck - and to start out, it only travels in the daytime, since nasty things come out at night.  Nassstier than us."*"And whatever it does, it stays away from the shoreline!  Wet.  Nasty.  Fisssh."*`),   // "Omen fades away...*" after it is a jump target and stays; the rename reaches it
  R('Ollum: Cademia', 0x1801, `The vision of Omen returns before you...*"Cademia.  Mother City.  Once you've lived in Cademia, no other place can be home."*"Keep your wits here - there are various miscreants that roam the back alleys, especially at night"*"Much lies buried beneath its ancient buildings - the city has much history that is now lost."*Omen fades away...*`, `The vision of Ollum returns before you...*"Cademia.  Mother City, precious.  Once it's lived in Cademia, no other place can be home, gollum."*"It keeps its wits here - miscreants roam the back alleys, especially at night, sss, nasty ones"*"Much lies buried beneath its ancient buildings, yesss, deep and dark - the city has history that's lost now.  We remembers.  We remembers everything."*Ollum fades away...*`),
  R('Ollum: danger', 0x1801, `The vision of Omen returns before you...*"Danger!  You are in great danger!"*"Beware what lies buried here - some things are best left undisturbed!"*"You must choose your own path, but what is here would destroy the world if unleashed!"*"And not even Alaric in his full powers would be able to stop this abomination!"*"It will tell you anything to get you to do its bidding - you must not even stoop to talk to it!"*"I beg you to leave well enough alone..."Omen fades away...*`,
    `The vision of Ollum returns before you, wringing its hands...*"Danger!  It's in great danger, precious!  Great danger!"*"Beware what lies buried here, gollum - some things is best left undisturbed, yesss, left in the dark!"*"It must choose its own path, but what's here would destroy the whole world if it got loose!"*"And not even Rick with all his powers could stop this abomination, sss!"*"It'll tell it anything to get it to do its bidding - it mustn't even stoop to talk to it!  Nasty liar!  Not like us, precious, we is honest, we is."*"We begs it, we begs, leave well enough alone..."Ollum fades away...*`),
  R('Ollum: Abydos', 0x1801, `The vision of Omen returns before you...*"Lost Abydos - now just a reminder of a great failure..."*"None of the Mages dare admit it, but Abydos was destroyed by their leader."*"The Mage Tavara destroyed the city when the people rejected his leadership."*"If you enter the tunnels below the city, you'll even find his workroom - but be careful."*"That place is guarded by a fearsome magical being that you'd call a daemon."*"Don't say you weren't warned."Omen fades away...*`,
    `The vision of Ollum returns before you...*"Lost Abydos, gollum - now just a reminder of a great failure, precious..."*"None of the Mages dares admit it, but Abydos was destroyed by their leader, yesss, their own leader."*"The Mage Tavara destroyed the city when the people rejected his leadership.  Sss.  We doesn't talk about the master.  We didn't say that."*"If it goes in the tunnels below the city, it'll even find his workroom - but careful, precious, careful."*"That place is guarded by a fearsome magical being that it'd call a daemon.  Big.  Hungry.  Not friends with us."*"Don't say it wasn't warned, gollum."Ollum fades away...*`),
  R('Ollum: four parts', 0x1801, `The vision of Omen returns before you...*"You are doing well - reforming the Crolna is most important to your success."*"But there are more parts to be found - a total of four."*"Getting the first two was the easy part - the next two will be a true test of your prowess."*Omen fades away...*`, `The vision of Ollum returns before you...*"It's doing well, precious - putting the Crolna back together is most important, yesss, most important of all."*"But there's more parts to find - four, gollum, four shiny parts.  We counted."*"Getting the first two was the easy part - the next two will be a true test of what it's made of, sss."*Ollum fades away...*`),
];

// ---- The scrolls of the Test (Tavara's), 0x0219 ----------------------------
const SCROLLS = [
  R('scroll 1', 0x0219, `Welcome, Human, to my little test for you.  It is not hard to pass, and will give you some of the skills you need to survive (though you may feel like a creature in a cage) - I hope that Omen did not startle you.  His appearance is strange, but don't let that deceive you. \n\nYou have already passed the first part of the test - you have read this note.  Next, you must pull that nearby lever to open the gate, leading you to the next room.  There you will find a locked trapdoor.  Find the key, open it, and then go down the ladder.`,
    `WELCOME, PUNY HUMAN, TO MY DIABOLICAL TEST!  MWAHAHAHA!  It is not hard to pass - for the merest worm could pass it, and a worm is all you are to ME - yet it shall grant you the pitiful skills you need to survive my later, far crueller schemes (you may feel like a creature in a cage; GOOD; you ARE one).  I trust my loathsome creature Ollum did not startle you.  His appearance is hideous, for I made him so, with these very hands, on a Tuesday. \n\nYou have already passed the first part of my test - you have read this note!  FOOL!  You have played directly into my hands!  Next, you must pull that nearby lever to open the gate, leading you to the next room of my labyrinth of DOOM.  There you will find a locked trapdoor.  Find the key, open it, and then go down the ladder, ever downward, into the darkness I have so lovingly prepared.`),
  R('scroll 2', 0x0219, `Sorry, the key is not in this chest, but good try.  Look to your south - notice anything interesting about the wall?  Try using it...\n\nOh, you might want to use one of the torches in this chest, it will provide some light for you if you wield it in your hands...`,
    `AH-HA!  The key is NOT in this chest!  DECEIVED!  Do you feel the sting of my cunning, little insect?  I laughed for an hour when I wrote this.  Look to your south - notice anything interesting about the wall, or is your feeble mind already crumbling before my genius?  Try using it...\n\nOh, you might want to use one of the torches in this chest, for it will provide some light for you if you wield it in your hands... yes, I am generous, in my way.  A benevolent tyrant of the dark.  Do not thank me.  It would only make it worse.`),
  R('scroll 3', 0x0219, `Ah, very good - very observant, finding that second secret door, but not all discoveries like this lead to reward, unfortunately.  However, this one does...`,
    `Ah, very good - very observant, finding that second secret door!  I underestimated you, worm... NO.  I never underestimate.  I merely allow you the ILLUSION of triumph, the better to crush it later.  Not all discoveries like this lead to reward, unfortunately for you - some lead to spikes, some to pits, some to a small room where I keep the screaming.  However, this one does lead to reward... FOR NOW.  MWAHAHA.`),
  R('scroll 4', 0x0219, `This room is trickier - the door is locked by a spell.  You have but one chance to get this one open - take that strange-looking object, what you would call a bomb.  Pick it up, use it to light it, and then toss it so it lands right next to the door.  Stand back and let time pass...`,
    `THIS room is trickier, my wriggling captive - the door is locked by a spell of MY OWN DEVISING, which took me the better part of an afternoon and is quite the most elegant thing ever wrought by a mind so vast as mine.  You have but ONE chance to get this door open - take that strange-looking object, what your primitive tongue would call a bomb.  Pick it up, use it to light it, and then toss it so it lands right next to the door.  Stand back and let time pass... and while you wait, reflect on how utterly you are in my power.  I certainly shall.`),
  R('scroll 5', 0x0219, `Not all levers are easily found - perhaps if you re-arranged things a bit here... (don't worry - all the crates are empty so it is easy for you to move them, and you don't need to waste your time searching them!)`,
    `Not all levers are easily found, and THIS one I have hidden with a malice so refined it borders on art - perhaps if you re-arranged things a bit here... (don't worry - all the crates are empty, for I emptied them myself, cackling, so it is easy for you to move them, and you need not waste your time searching them; your time belongs to ME now, and I shall spend it as I please!  MWAHAHAHAHA!)`),
];

// ---- The names, everywhere ---------------------------------------------------
const NAMES = [
  // the name table is a data edit below: its pointers are not the form the
  // relinker follows
  // every mention, in every script (an edit with no resource is every script, each allowed to match nothing)
  ...[['Alaric', 'Rick'], ['Magpie', 'Piemag'], ['Hadrian', 'RAMBO'], ['Emesa', 'Emetic'], ['Hector', 'Hecky']]
    .map(([a, b]) => ({ ...T('mentions of ' + a, null, a, b) })),
  // Omen only where it is the creature: Prusa's prophecy (0x021D) counts
  // its Omens Five, a common noun, and keeps them.
  ...[0x0242, 0x10EA, 0x1428, 0x1801, 0x1CC3].map(r => ({ ...T('mentions of Omen', r, 'Omen', 'Ollum'), optional: true })),
  // the keyword lists: the new name beside the old, wherever the old is answered
  ...[['alar', 'rick'], ['magp', 'piem'], ['hadr', 'ramb'], ['emes', 'emet'], ['hect', 'heck']].flatMap(([o, n]) => [
    // inside a list first: the end-of-list edit would otherwise make an
    // "alar," for the inside edit to match again
    { ...T('keyword ' + o + ' inside a list', null, o + ',', o + ',' + n + ',') },
    { ...T('keyword ' + o + ' at the end of a list', null, o + NUL, o + ',' + n + NUL) } ]),
];

/* The name table (0x0201), what is drawn over a head: a count, then 256
   words whose top half is a tag (0x9165 on every entry) and whose low half
   is the offset of a NUL-terminated string in the same resource. That is
   not the self-pointer form the relinker follows, so a name of a different
   length would leave every pointer after it stale (the first build did,
   and delvmod could no longer read the table). Laid out afresh instead:
   the same header, the same tags, the strings renamed, the offsets
   recomputed. */
const NAME_TABLE = { what: 'the name table', resid: 0x0201, fn: (b) => {
  const RENAME = { Alaric: 'Rick', Magpie: 'Piemag', Hadrian: 'RAMBO', Emesa: 'Emetic', Hector: 'Hecky', 'LKH Guard': 'LKH Bro', Omen: 'Ollum' };
  const n = ((b[0] << 8) | b[1]) & 0x0FFF;
  if (n !== 256 || (b[0] & 0xF0) !== 0x90) throw new Error('the name table is not an array of 256');
  const tags = [], names = [];
  for (let i = 0; i < n; i++) {
    const q = 2 + 4 * i, tag = (b[q] << 8) | b[q + 1], off = (b[q + 2] << 8) | b[q + 3];
    if (tag !== 0x9165) throw new Error('entry ' + i + ' has tag 0x' + tag.toString(16) + ', not 0x9165');
    let e = off; while (e < b.length && b[e] !== 0) e++;
    let s = ''; for (let k = off; k < e; k++) s += String.fromCharCode(b[k]);
    tags.push(tag); names.push(RENAME[s] !== undefined ? RENAME[s] : s);
  }
  for (const k of Object.keys(RENAME)) if (!names.includes(RENAME[k])) throw new Error('the name table has no ' + k);
  const out = [b[0], b[1]]; const ptrs = []; let off = 2 + 4 * n;
  const strs = [];
  for (let i = 0; i < n; i++) { ptrs.push(off); for (const c of names[i]) strs.push(c.charCodeAt(0)); strs.push(0); off += names[i].length + 1; }
  for (let i = 0; i < n; i++) out.push((tags[i] >> 8) & 0xFF, tags[i] & 0xFF, (ptrs[i] >> 8) & 0xFF, ptrs[i] & 0xFF);
  return Uint8Array.from(out.concat(strs));
} };

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const [htmlPath = 'index.html', dataPath, outDir] = process.argv.slice(2);
  if (!dataPath || !outDir) { console.error('usage: voices_patch.mjs index.html <Cythera Data.data> <out dir>'); process.exit(2); }
  const ok = buildPatch({ htmlPath, dataPath, outDir, name: 'Cythera Voices of the Hall',
    description: 'The text fixes, and the people of Land King Hall with new names and voices: Rick the surfer, Piemag who speaks as Yoda, Ollum who speaks as Gollum, Hecky who worships his daddy, RAMBO, Emetic who loathes flatbread, LKH Bro from the gym, and the Test’s scrolls as villainy.',
    edits: [], dataEdits: [NAME_TABLE], textEdits: [...textFixEdits(), ...RICK, ...PIEMAG, ...RAMBO, ...EMETIC, ...HECKY, ...BRO, ...OLLUM, ...SCROLLS, ...NAMES] });
  process.exit(ok ? 0 : 1);
}
