#!/usr/bin/env node
/* A builder, not a check: the text fixes, and on top of them a voice for
   each of the people of Land King Hall, every line they speak, with new
   names. (24 September 2026, at the maintainer's word; a variant for fun.)

   Usage: node utilities/voices_patch.mjs index.html "<Cythera Data.data>" <out dir>

   Alaric is Rick, who also answers to Al, a surfer; Magpie is Piemag and
   speaks as Yoda does; Omen is Ollum and speaks as Gollum does; Hector is
   Hecky, an infant who worships his daddy; Hadrian is RAMBO; Emesa is
   Emetic, who loathes being asked for flatbread and bakes it foul on
   purpose; the hall's guard is LKH Bro, from the gym; and the scrolls of
   the Test, which the game's own text gives to the mage Tavara (Omen names
   him, and the Test's notes speak of Omen as their author's creature), are
   villainy without restraint.

   How it holds together: each spoken line is replaced whole, matched as the
   text fixes leave it, keeping its click marks, line breaks, the fragments
   the script joins mid-sentence and every highlighted @word, since a
   highlighted word must still begin with a keyword the script answers. The
   names change in the name table (what is drawn over a head), in every
   mention across every script, and in the keyword lists, which gain the new
   name beside the old so that either can be typed: "alar" keeps working and
   "rick" joins it. "Al" is not a keyword, since typed words match by their
   first letters and "al" would catch "alchemy". Omen has no keyword; the
   guard's is "guar" and stays. */
import {fileURLToPath} from 'node:url';
import {buildCast} from './hall_lines.mjs';

export const CAST = {
  name: 'Cythera Voices of the Hall',
  description: 'The text fixes, and the people of Land King Hall with new names and voices: Rick the surfer, Piemag who speaks as Yoda, Ollum who speaks as Gollum, Hecky who worships his daddy, RAMBO, Emetic who loathes flatbread, LKH Bro from the gym, and the Test\u2019s scrolls as villainy.',
  names: { Alaric: 'Rick', Magpie: 'Piemag', Hadrian: 'RAMBO', Emesa: 'Emetic', Hector: 'Hecky', 'LKH Guard': 'LKH Bro', Omen: 'Ollum' },
  // Omen only where it is the creature: Prusa's prophecy (0x021D) counts its Omens Five, a common noun, and keeps them.
  omenResids: [0x0242, 0x10EA, 0x1428, 0x1801, 0x1CC3],
  keywords: [['alar', 'rick'], ['magp', 'piem'], ['hadr', 'ramb'], ['emes', 'emet'], ['hect', 'heck']],
  lines: {
    rick_description: `Before you stands a sun-bleached older dude with a totally gnarly tan`,
    rick_desperate: `, but, like, seriously bummed out.`,
    rick_satisfied: `, looking totally stoked.`,
    rick_relieved: `, looking mellow and, like, at one with the universe, man.`,
    rick_the_dark_ending: `Just before your vision fades completely, the face of Rick wavers, and the vibe goes seriously dark.*`,
    rick_possessed: `"Yes, thank you, foolish mortal - without you, we never would have gained control of he who was once Rick."*"With the powers of the Crolna, Land King Hall and all humanity behind us, we shall make short work of the Seldane."*"And then we can rid ourselves of the humans as well - dude, our victory is, like, totally sealed."*`,
    rick_piemag_vision: `Just before it fades completely, the vision of Piemag appears before you.`,
    rick_bahoudin_thanks: `*"Thank you for curing Rick, Bahoudin does.  Alive today were Rick's mother, Chrysothemis, thank you she would, hmm."*"Alas, alive she is not.  Still, her husband, father of Rick, Bahoudin, thank you he does, for saving his son.  Yes."*`,
    rick_first_speech: `"Duuude - you're up!  Righteous.  We were, like, majorly worried you got wiped out."*"So, okay, I should probably explain the sitch.  Name's Rick - or Al, whatever, bro, I answer to both - and you are now in the land of @Cythera.  Gnarly, right?"*"You got summoned in a final, desperate, hail-Mary kinda move to save Cythera and its ruler from total chaos and, like, madness."*"I'm that ruler, dude, and I've got this special @bond with the land and the people of Cythera.  For over two hundred years I've used my magic to keep the whole scene mellow and prosperous."*"Bummer is, the last coupla years my mojo's been fading, and with it Cythera's started, like, wiping out into chaos."*"It's like that bond is dissolving, the land's changing somehow. I don't get it, man."*"The more impotent I get, the more it harshes my mellow to watch it all slip away, like waking up from a totally epic dream..."*"So I trusted the fates to summon an outsider, from @Mater Theia herself, 'cause only an outsider can see through this fog that's, like, blocking my vision."*"You, obviously, are that outsider.  Don't think I did this on a whim, bro - it cost me most of my remaining power to pull it off."*"I gotta trust you to help me.  Sorry about the danger and all, but you're my, and Cythera's, last chance.  No pressure, dude."`,
    rick_rude_of_me: `"I'm Rick - or Al, take your pick - did I tell you already?  My bad, dude, totally rude of me.\n"`,
    rick_keeper: `"I'm, like, the keeper of the land of Cythera,`,
    rick_stranger: ` though some days I feel like a total kook, man."`,
    rick_look_you_over: `"Hm, lemme check you out, dude..."*`,
    rick_that_should_help: `"There, that should help.  Sweet."`,
    rick_good_shape: `"Dude, you're looking totally shredded as it is."`,
    rick_stained: `"Sorry, bro, but your soul's got way too much bad karma for me to hose off."`,
    rick_register: `"Sorry, dude, can't help you till you've registered this software.  Not cool, man."`,
    rick_no_experience: `"Dude, you haven't logged enough waves for more training yet."`,
    rick_amulet: `"Here, take this amulet, bro - it's got my symbol on it.  Wear it around your neck and it'll save your life if you, like, totally wipe out."*"You can also use it to bring a buddy back from the halls of death, but heads up, it's only got so many charges in it."*He gives you an amulet on a gold chain, and a shaka.*`,
    rick_quarters: `*"I got some quarters set up for you, dude - Piemag will show you around."*`,
    piemag_follow: `"Follow Piemag, you should.  Hmm, yes."*`,
    piemag_the_library: `Piemag points to the end of the hall to the north.*"At the end of the hall, the Library is.  Yes."*"Much learning, in there, found can be, from the books by elders written.  Learn, you must.  Do you well, it might, hmm."*`,
    piemag_the_quarters: `"Quarters for you, these are.  Provisions, in there, are."*"Yours, the things in your quarters are.  Serve you well, they shall."*"But steal from others, you must not.  Honorable, Cythera is.  Serve you ill, such deeds will.  Yes, hmm."*Piemag looks around quickly.*"The fool, Piemag is.  But even Piemag knows: dangerous, your journey will be, young one."*"Learn what you can, you should.  Come and go, important visitors do.  But unique, you are."*"Across the hall, for the nonce, Demodocus stays.  Talk with him, Piemag would, were Piemag you."*"Also, ask around, one might, to see if somebody would like to @join you on your quest, hmm..."`,
    rick_help_me: `"Please, dude, do what you can to help me out.  I'd be so stoked."`,
    rick_odemia: `"Odemia's the closest city, bro - head east and just, like, hug the coast."`,
    rick_the_land: `"Yeah, dude, Cythera is the land.  Whoa."`,
    rick_one_again: `"I'm, like, totally one with the land again, thanks to you, bro.  Cowabunga."`,
    rick_the_bond: `"I am, or like, was, at one with the land and its people, man.  I've provided all their basic needs - a bountiful land, epic mild weather, and peace, dude, peace."*"But now it all seems to be slipping away - a void where I can't see squat or do squat.  Total bummer."`,
    rick_mater_theia: `"Mater Theia, Earthmother, dude, at least before the @Journey brought us here.  Now we're, like, without Mater Theia, but there are @stories, bro."`,
    rick_stories: `"Stories tell of a power, formed of Earth, that still walks the land, who we call Metics.  Gnarly, right?"*"But I doubt they're still around, or I'd have picked up their vibe, man."`,
    rick_the_journey: `"We're not from here, dude, but from the same Earth you are. We lived on this island called Thera, till Enesidaone, like, reclaimed it."*"Not without warning, though - this stranger shaped like the Holy Bull rocked up and told us to bail.  We watched Thera get wiped out from our boats, way out past the break."*"That night the most gnarly storm ever tossed us around, till in the morning we woke up washed up on the beach near what'd become Cademia.  Epic wipeout, man."*"Or so goes the legend.  I'm not a @historian, bro - maybe ask somebody else..."`,
    rick_history_forgotten: `"Dude, some days I can't remember what happened yesterday, let alone, like, ancient history."*"For some reason, though, the number 201 feels important.  If you figure out why, tell me, bro..."`,
    rick_history_remembered: `"My history?  I remember a few parts, dude.  Living with my mom as a grom in Catamarca.  When she died, I left Catamarca to, like, roam."*"How I survived, no clue, man.  I think I was looking for the exiled Mages, 'cause I felt like I had powers way beyond the normals, and I wanted to learn about 'em."*"Instead I wandered into a cave, but it wasn't a cave. I crossed this bridge of stars, bro, and found an abandoned hall or temple or something."*"Who built it, no idea.  It was empty and abandoned, but this great power was, like, calling to me."*"I remember standing on the edge of the Abyss, and I just let go, dude - surrendered to it, became one with it, with the Land.  Most epic drop-in ever."*"That's when I became the Land King.  Don't know how long I stood there - years, for sure.  And in the end, the bond was, like, complete."*"I knew then the Tyrants had to go.  So I ended 'em - and out of that came the whole Houses and Judges scene."*"And now it all seems to be failing - maybe my session's over, man..."`,
    rick_201: `"Yeah, dude.  That's the day my mom passed away."`,
    rick_201_unknown: `"That number feels important, bro, but I got no idea why."`,
    rick_metics: `"Metics are the dudes who lived in Cythera before we showed up.  Their ruins are outside Pnyx, and I hear more got found in the Swamp of Khalkis"*"Go find a Freemage named Timon, bro - he's totally studied 'em."`,
    rick_enesidaone: `"Enesidaone, Mater Theia, the old gods, man.  They don't steer our fate anymore. Bummer is, I'm the closest thing to a deity now, dude..."`,
    rick_chrysothemis: `"Chrysothemis was my mom, dude - her I remember for sure."`,
    rick_mother_remembered: `"Yeah, she was my mom - I remember now, dude.  It was in 201 that she passed away.  Yeah, that's where it all started."*"I can remember parts of my @history again.  Who knows for how long, though, man..."*`,
    rick_mother_missing: `"My mom, I remember, but not quite, bro - a chunk of my memory's, like, gone there..."`,
    rick_mother_well: `"Chrysothemis was my mom - her I remember totally clearly now, dude."`,
    rick_father: `"My dad?  Nothing, man - maybe I did once, but not now..."`,
    rick_piemag: `"Piemag might be my fool, dude, but he's a totally trusted advisor.  Weird syntax, though."`,
    rick_excuse_me: `"Uh, come again, dude?"`,
    rick_stares: `He just stares off at the horizon, like he's checking the swell.\n`,
    rick_thanks_to_you: ` thanks to you, bro."`,
    rick_the_good_ending: `"Dude, you did it!  It's remarkable - amazing.  I'm, like, totally out of words, man."*"It's like a fog just lifted, like I can see again.  Every blade of grass, I feel it, bro."*"The land's been hurting, but you helped cure it, and me with it.  So stoked."*"I'll keep this artifact safe - its powers have, like, re-tuned my senses.  Radical."*"I don't know how to repay you, dude, not just for me, but for the whole land."*"I'll send you back to your own land, like I promised.  Thanks again, bro.  Catch you on the flip side."*Rick throws a shaka, waves his hands before you, and your vision grows dark...*`,
    piemag_on_the_throne: `You see a hunchback dressed in motley, sitting on the throne.\n*"Warm, Rick's chair, Piemag is only keeping.  Yes.  That is all, hmm."`,
    piemag_standing: `You see a small hunchback dressed in motley, with a pleasant demeanor and very large ears.\n`,
    piemag_master_first: `"Talk to the master first, you must.  Hmm.  Yes."`,
    piemag_names: `"Many names, Piemag has.  Hmm, yes.  Many."`,
    piemag_fool: `"The King's Fool, Piemag is!  Enough, is that not?  Hmm?"`,
    piemag_place: `"Sorry, Piemag is.  With Rick, Piemag's place is.  Go, Piemag cannot."`,
    piemag_story_untold: `"A story that told cannot be, it is.  Hmm.  No."`,
    piemag_history: `"Everywhere, history is.  But a rock its history, nobody asks, hmm."*"The history of Piemag, a @story that is.  But the history of Rick, a @tale that is.  Yes."`,
    piemag_the_tale: `"The tale of Rick?  History, his story is!  Ho ho ho."*Piemag laughs and capers as if the best joke ever invented, he has told.*"Rick it was that the rule of the Tyrants destroyed, and the Mages from exile brought back."*"He it was that government set up, as today it stands.  But how the power for this feat he gained, none know."*"Or at least, say it none will.  No one, none is.  And not one, no one is.  And two, not one is.  Hmm."*Piemag again with delight beams.`,
    piemag_more_stories: `"More stories, perhaps, share we will..."`,
    piemag_the_bond: `"A magical bond with the land, Rick has, which its prosperity ensure lets him.  The Land King, that is why called he is"*"And Land King Hall, this place thus is.  Hall of the Land King.  Hall of Rick.  Hmm."*"In truth, King of more than just the Land, surely he is."`,
    piemag_not_welcomed: `"A place where welcomed Piemag is, that is not."`,
    piemag_welcomed: `"Welcomed there, Piemag is.  Or at least, was.  Hmm."`,
    piemag_wizards: `"City of Wizards.  How to treat Piemag, they know.  Yes."`,
    piemag_metics: `"A legend, Metics are.  But so is Piemag.  And true, both are."*"Knows them, Piemag does.  Welcome by them, Piemag is not.  No."`,
    piemag_seldane: `"Seldane, Seldine - all the same, are they not?  Metics by any other name, they are.  Hmm."`,
    piemag_a_son: `"A son, Piemag has, and met him, you have.  @Three that are one, he is.`,
    piemag_no_more: `  More, say Piemag cannot.  No.`,
    piemag_one: `"Easy to say that one is, it is.  Or is it?  Truly say what one is, and what one isn't, can one?"*"Really one, is one?  Or perhaps two?  Mayhaps even three, hmm?"`,
    piemag_two: `"Matter not, two does.  But three?  Hmm."`,
    piemag_four: `"Four, could there be?  Why, with man, five there can be!  Ho ho."`,
    piemag_five: `"Lost, two of five are?  Then but three, there are.  Yes."`,
    piemag_three: `"One, Jhiaxus is.  One, Jinrai is."*"Two, Bahoudin is.  One, Chrysothemis is."*"Three, Rick is.  Hmm."`,
    piemag_not_ready: `"Ah, three.  Important, that is.  But ready for that knowledge, you are not.  Patience."`,
    piemag_mother: `"Mother of Rick, that one is."`,
    piemag_the_name: `"Know the name, you do.  A dangerous tool, it is.  But a tool nonetheless, hmm."*"A tool to open, a tool to close."*"A tool to build, a tool to destroy."*"A tool to heal, a tool to poison.  Yes."`,
    piemag_sabinate: `*"Right, Sabinate is, perhaps.  But wrong when right, one can be."*"Fears, Piemag does, that the last best hope for Rick it is.  Great, the risk is.  Hmm."`,
    piemag_visions: `"Deep to the truth of what is, and what must never be, not all visions see.  No."`,
    piemag_old_name: `"An old name, that is.  Used anymore, it is not."`,
    piemag_motives: `"Many motives, many people have.  Bode well, not all do."`,
    piemag_jinrai: `"Dangerous, the people of Jinrai are.  Very much so, yes."`,
    piemag_the_dead: `*"Remember well, you must: walk, the dead do not."`,
    piemag_glances_at_rick: `He glances briefly at Rick, as if to see if listening he is.*"A story that for Piemag to tell is not, that is."`,
    piemag_not_safe: `"Please - safe, that name is not.  Never uses that name, Piemag does."`,
    piemag_bahoudin: `He glances around briefly.*"Piemag and Bahoudin, many stories there are.  True, that story is.  Hmm."*`,
    piemag_the_key: `"Yes, truth Jhiaxus speaks.  Yield it to you, Piemag shall.  But great danger, there is."*`,
    piemag_fears: `"Great danger, for all.  True, Piemag's fears come..."*"Save us all, you shall..."*"...or destroy us all."*"The power to choose, you alone have."*"Better than Sabinate or Jhiaxus, Piemag sees.  But unseen, this is.  Clouded, the future is."*"Their own motives, Sabinate and Jhiaxus have.  Remember this, you must."*`,
    piemag_not_to_tell_three_times: `"For Piemag to tell, that story is not.  Hmm."`,
    piemag_the_king: `"The King, Rick is, and Rick, the King is.  @Bonded to the @land, he is.  Yes."`,
    piemag_land_and_water: `"Land and water, water and land - one, those two are not.  Except for two, who two and three are.  Confusing, this is.  Hmm."`,
    piemag_ignae: `"A trickster, old Ignae is.  The sly one, he is.  Yes."`,
    piemag_tourguide: `"Tourguide, Piemag has played for you once.  Twice, Piemag will not.  Hmm."`,
    rambo_description: `You see an older warrior with a red bandanna, a thousand-yard stare, and a knife the size of your forearm.*`,
    rambo_greeting: `"They drew first blood, not me.  Name's RAMBO.  Captain of Rick's Guard.  @Trainer.  Welcome to our world, stranger.  Don't push it."`,
    rambo_again: `"You again, stranger.  Nothing is over`,
    rambo_name: `"RAMBO.  Captain of Rick's Guards.  That's all you need to know."`,
    rambo_job: `"I run the guards that protect Rick and Land King Hall.  To survive a war, you gotta become war."`,
    rambo_proud: `"Hecky's done his service.  I'm proud.  I don't say that twice."`,
    rambo_served_with_honor: `"He served you with honor.  Didn't he.  Good.  In here he's still a boy - out there, he's a soldier."*`,
    rambo_hecky_blushes: `Hecky blushes and hugs RAMBO's leg...*`,
    rambo_how_is_my_son: `"My boy.  How's he doing.  He serving you with honor?"*`,
    rambo_indeed: `"I am.  Live for nothing, or die for something."`,
    rambo_died: `"Hecky's dead.  He died in my service.  I'm sorry.  I truly am."*`,
    rambo_choked_up: `RAMBO stares at the wall.  His jaw works.  Nothing comes out for a long moment.\n*"Thanks for telling me.  We all knew the risks.  Back home, nobody knows."*"A warrior can know no better death than dying for a cause that's right and just.  When you're pushed, killing's as easy as breathing."*`,
    rambo_fine_son: `"Hecky's a fine son.  He'll serve you with honor.  Or he'll answer to me."`,
    rambo_fine_lad: `"My boy Hecky's a fine lad.  He'll be a great warrior and leader, once he's seen some action.  Right now he mostly sees me."`,
    rambo_permission_given: `"Take him.  Nothing'd make me prouder.  He'll serve you with honor.  Bring him back or don't come back."*`,
    rambo_train: `"I can @train you in that.  It won't be pretty.  Your choice."`,
    rambo_eioneus: `"I remember him.  Bright young mage.  Magically enhanced weapons.  My kind of research."*"Haven't seen him in years.  Might be worth tracking down.  I'm good at tracking."*`,
    rambo_farewell_thanks: `"Move out.  And... thanks."`,
    rambo_farewell: `"Move out."`,
    rambo_a_favor: `*"Wait.  One thing.  A favor.  I don't ask favors."*"My mother died recently.  With my duties here I can't honor her the way she deserves."*"Put these flowers on her grave.  Graveyard in Catamarca.  Don't make me ask twice..."`,
    rambo_andra: `"Good.  Her name was Andra.  She's buried next to my father Lycus.  Now get out of here"`,
    rambo_declined: `"Understood.  Forget I asked.  Nothing is over."`,
    rambo_mother: `"Andra.  My mother.  Don't."`,
    rambo_father: `"Lycus.  My father.  He taught me everything."`,
    rambo_no_help: `"Can't help you there.  Ask someone who talks."`,
    emetic_description: `You see an older woman, floury to the elbows, with the thousand-yard stare of someone asked for flatbread one too many times.*`,
    emetic_greeting: `"Greetings, stranger, welcome to our world.  I am Emetic, Rick's @cook.  And no, before you ask - no flatbread."*"If there's @anything I can do for you in your @journeys, anything at all that is not flatbread, please, just ask..."`,
    emetic_again: `"Greetings again, stranger.  Don't say it.`,
    emetic_name: `"I am Emetic, `,
    emetic_cook: `"I am the @cook for @Rick - my specialty is bread.  Real bread.  Not flatbread.  Everyone wants flatbread.  I loathe flatbread."`,
    emetic_husband: `"Yes, my husband is RAMBO, captain of the guards here...  He shouts his own name a lot."*"A loving father, and a strong man, although Rick's ailing health has him troubled, and he only eats his flatbread cold, out of a tin."*"You'll find him at the Land King's side most of the time these days, sharpening things...."`,
    emetic_beloved: `"Yes, RAMBO is my beloved husband..."*"He works so hard to protect and care for Rick in these times of strife, I @worry about him...  He hasn't taken the bandanna off since spring."`,
    emetic_worry: `"He rarely sleeps, and has become quite withdrawn of late..."*"I think his @concern for Rick is overpowering the man I love; it's quite a burden for him to bear, and he takes it out on the woodpile."*"You see, RAMBO's sworn duty is to protect Rick, and Land King Hall, but now that an unseen force has afflicted his liege, he is left powerless to stab anything about it."`,
    emetic_concern: `"RAMBO's concern for Rick has in turn led to my concern for my husband."*"He hasn't even had time to properly @mourn the passing of his mother, let alone tend to his family that still lives - and the family would like some proper bread, thank you."`,
    emetic_mourn: `"RAMBO's kindly mother passed away recently in Catamarca."*"She was such a kindly old woman, but one with much life left within her.  She never once asked me for flatbread."*"A terrible shame to have it stolen from her."`,
    emetic_concerned_for_rick: `"I too am concerned for Rick..."*"I do what I can, providing him with nourishing food to ease his weary bones and troubled brow.  He asks for flatbread.  He gets soup."*"These are troubled times, stranger.  I do hope you can help him, and by doing so, help us, and all of the land of Cythera, and its dreadful flatbread habit."`,
    emetic_son: `"Hecky is our son - we are very proud of him.  He's a little young for his age.  He still calls his father Daddy.  Loudly."`,
    emetic_ask_rambo: `"You'll have to talk to RAMBO about that.  Speak slowly, and don't stand too close."`,
    emetic_honor_to_cook: `"It is an honor to cook @food for Rick.  Real food.  With a crust.  That rises."`,
    emetic_piemag: `"Piemag is quite the jester, isn't he?  Ask for flatbread, he does.  Backwards.  Every day."`,
    emetic_journeys: `"Oh, I'd imagine you'll be traveling far and wide soon.  Be careful, keep your eyes open, and perhaps see if you can get some people to help you along the way."*"Nothing like having friends to help you out of a rough spot...  Friends who bring their own bread."*"I don't travel much myself, so I don't know much about the goings on in the land, but my @husband is quite worldly.  He's been to some very loud places."*"Perhaps he can tell you a thing or two?  Or grunt it?"`,
    emetic_food: `"Well, I can offer you some @food if you like.  It will be flatbread.  It is always flatbread.  I make it taste like a wet sandal on purpose, and still they come..."*"Who knows how long it will be before you're able to find another place to @catch a meal?  Somewhere with proper bread, I hope, for your sake."*"You'll be able to get a something to eat at various @Inns, of course, but for a price.  Worth it.  Trust me."`,
    emetic_animals: `"Animals roaming in the wilds of Cythera are a good source of meat, but be careful not to wantonly slaughter animals in town."*"They invariably belong to someone, and they'll be none too pleased with you."*"Please... if you do kill such wild animals for food, do so quickly and mercifully...  Meat.  Now there's a thing you can cook without anyone asking you to flatten it."`,
    emetic_inns: `"Oh, just about every village in Cythera has an Inn... a place where you can get a hot meal, and a good night's sleep."*"I don't condone many of the sort who hang about there for the drink, however...  Though at least the drunks don't want flatbread."*"And of course, you're always welcome to come back here instead, where I can give you something to eat before you turn in.  It will be flatbread.  It will be awful.  This is on purpose."`,
    emetic_hungry: `"Are you hungry?  Are you about to ask me for flatbread?  Are you sure?"`,
    emetic_gives_food: `"Fine.  FINE.  Here."*She slaps a flatbread into your hands.  It smells faintly of resentment and old fish\n`,
    emetic_ask_when_hungry: `"Well, ask me if you are hungry.  Everyone does.  Every.  Single.  Day."`,
    emetic_refresher: `"Need a refresher?  I can understand - you've more important things on your mind than my suffering."*`,
    emetic_learn_bread: `"Would you like to learn how to make bread?  Real bread?  Or are you another flatbread person?"`,
    emetic_other_time: `"Perhaps some other time.  When you've grown a palate."`,
    emetic_recipe: `"Baking bread isn't that hard - Take some flour and spread it out."*"Take some water and add to the flour."*"Take a rolling pin and roll out the dough.  Not too flat.  Never too flat.  Do you hear me?"*"Take the finished dough and bake it, and you're done!  If it comes out flat, it's your own fault, and I'll know."`,
    emetic_farewell: `"Farewell.  Eat something decent."`,
    emetic_not_familiar: `"I'm sorry, but I'm not familiar with that.  Unless it's a kind of flatbread, in which case I refuse to be."`,
    hecky_weapon: `"It'll work as a weapon, but Daddy only teached me the pointy ones..."`,
    hecky_description: `You see a young warrior with a look of fire in his eyes, a thumb in his mouth, and a wooden sword that says DADDY on it.*`,
    hecky_greeting: `"Ooh!  You're the one Rick summoned!  My name is Hecky, and I'm honored to meet you!  Have you met my DADDY?  He's the bestest."`,
    hecky_my_leader: `"Yes, my leader!  What can I do?  Is it something Daddy would do?"`,
    hecky_service: `, how can I be of service?  Daddy says I'm very helpful."`,
    hecky_earthquake: `"This is our training room, where Daddy trains me!  But with the damage from that @earthquake, I dunno"`,
    hecky_tremors: `"This area always had little wobbles, but this is the first one that broke stuff.  I hid behind Daddy."*"Come to think of it, there's been more wobbles here since Rick started getting poorly."`,
    hecky_name: `"I'm Hecky!  Our legends tell of a great @warrior called Hector, but mostly I want to be like my @father, 'cause he's my DADDY and he's the strongest."*"So you're the @stranger Rick summoned here to help him?  Does Daddy know?"`,
    hecky_job: `"I'm a warrior!  Or I will be, like Daddy.  Daddy's a warrior.  Did you know Daddy's a warrior?"`,
    hecky_father: `"My daddy is RAMBO, and he's the head of Rick's guards, and it's very honorable, and he can lift a whole horse, probably"`,
    hecky_stranger: `"Well, I hope Rick knows what he's doing.  No offense, but you don't look like much of a hero to me...  Not like Daddy."*"But looks can be deceiving, my @mother always says, mostly about Daddy's flatbread face"`,
    hecky_mother: `"Mommy's right around the corner in the kitchen, usually.  Don't ask her for flatbread.  She gets scary."*"She's a kind-hearted soul, and it makes me sad to see her working so hard."*"She's here mostly to be close to my @father, I think, 'cause everybody wants to be close to Daddy, and she does seem to like her @work."`,
    hecky_work: `"Well, she makes all the meals for everybody in Land King Hall, even @Rick himself!  And Daddy!  Daddy eats the most."*"Say, I bet if you asked her, she'd cook you a hot meal...  Just don't say the F-word.  Flatbread.  Oops."`,
    hecky_rick: `"Rick is more than just our ruler, he glues the land together somehow, in a way I don't get.  Daddy probably gets it."*"I dunno exactly what's going on, but I do know that as Rick got poorly, the land got @suffered too."`,
    hecky_suffered: `"Lots has happened in Cythera that would've been unthinkable a few years ago...  I was even littler then."*"It's like the land has a tummy bug, and can't fight back against agents of @evil,"`,
    hecky_criminals: `"I've heard stories of @criminals roaming rapant, and stranger still, of odd creatures roaming about.  Daddy would biff them all."`,
    hecky_cowards: `"I'd love to give them a taste of their own medicine!  Dark-hearted meanies!  Daddy says they drew first blood."*"Cythera should go back to being the nice land it was..."`,
    hecky_warrior: `"Yes, I want to make Daddy proud of me, my @father, and maybe make a name for myself too, but mostly Daddy."*"I've been @training and studying the ways of a warrior.  Daddy's ways.  Daddy has all the ways."`,
    hecky_training: `"Daddy helped me with that; he's a great warrior and a patient teacher and he gives the best piggybacks."*"I think I've got past the point where training alone can help me, though...  Daddy says I need to see the elephant.  I don't know what that means."`,
    hecky_honor: `"Without honor there's no meaning to life.  Daddy said that.  Most people in Cythera like honor a lot, but me more than most, 'cause Daddy."`,
    hecky_already_following: `"But I'm already following you...  Like I follow Daddy."`,
    hecky_ask_father: `"I'd be honored!  But I gotta do what my @father says - you'll need to ask Daddy first.  Ask nicely."`,
    rambo_permission: `*"Take the boy.  It'd honor me.  He's ready.  He's been ready since he was four."*`,
    hecky_thank_you_father: `"Thank you, Daddy!  Thank you thank you thank you!  I'll make you so proud!"*`,
    hecky_father_said_yes: `"Daddy said yes?  DADDY SAID YES!  I'm honored to join you on your most noble quest!  Can we tell Daddy about it after?"`,
    hecky_rejoin: `"It'd be the highest honor to come along again!  Daddy will be so pleased!"`,
    hecky_served_poorly: `"Did I do a bad?  Are you gonna tell Daddy?"`,
    hecky_woe: `"Waaah!  Please please give me another chance, I'll prove myself, please don't tell Daddy!"`,
    hecky_very_well: `"Okay.  You have your own destiny to follow - come find me if you ever need a companion.  I'll be with Daddy."`,
    hecky_not_in_party_twice: `"I'm not in the party right now.  Maybe I should @join you!  Daddy would want me to."`,
    hecky_wait: `"I'll wait right here till you come back.  I won't move.  Daddy taught me."`,
    hecky_gladly: `"Yay!"`,
    hecky_not_waiting: `"I'm not waiting to rejoin you right now.  Maybe I should @join you!"`,
    hecky_anything_else: `"Let me know if there's anything else I can do...  I can do lots.  Daddy showed me."`,
    hecky_until_we_meet: `"Bye-bye!  Till we meet again!  I'm gonna go find Daddy!"`,
    hecky_confused: `"You confuse me with your words.  Daddy doesn't use words much."`,
    bro_description: `You see an extremely jacked guard, flexing at nothing in particular.*`,
    bro_job: `"I guard Rick here in Land King Hall, bro.  Guarding's basically cardio.  You lift?"`,
    bro_goodbye: `"Later, bro.  Never skip leg day."`,
    bro_not_permitted: `"Bro, I'm just a guard, I'm not allowed to talk about that.  Gains, though?  I can talk gains all day, bro."`,
    the_hero_dies: `You die, not knowing the fate of Rick.`,
    ollum_first_vision: `A strange-looking face suddenly fades into view before you, all eyes and teeth...*"Poor little human, yesss - so far from home, and so far from the truth, precious..."*"It knows, doesn't it, gollum, that Rick is not all he says he is.  True, he is bound to the land, yesss, but as a usurper, a thief, a nasty thief."*"He doesn't belong in the big chair, no, and he upsets the balance of the whole world by sitting in it, precious."*"And you, my friend, my precious friend, are just another puppet of his.  Now is the time of change, yesss, and you are at the pivot point.  We sees it."*"But which way will the balance swing?  To the East?  Or to the West?  Gollum, gollum."*"And us?  We are Ollum, precious, and our master told us to watch for one like you.  Nice and juicy, sss."*`,
    ollum_second_vision: `"It costs us, precious, it costs us so much, to come to it like this, as a vision, to warn it and guide it, protect it and teach it, yesss."*"Know this, it must - there's more going on here than meets the eyes, gollum, a power struggle as old as the world itself."*"And in this struggle it is trapped, like a fish, a wriggling fish.  If it ever wants to be free, it listens to us, precious, it listens good."*"Rick must be destroyed to fix the land, yesss, and in the end, it will do this.  It will.  We sees it."*"To help it with its destiny, we has a small gift, precious, to prove our word.  We doesn't lie.  Not to it."*"But first it must learn the ways of the land, so our master has made a little test of what it can do, gollum."*"It must sharpen itself.  As a sword is tempered, so must it be, sss."*"Find its way out of these proving grounds, and along the way it might find its reward.  Might.  If it's clever, precious."*"Follow our counsel and it will be well rewarded - ignore it and it goes in the pot, yesss."*"Until we meets again, keep its guard up, and trust not what its eyes behold.  Gollum!"*`,
    ollum_first_piece: `The vision of Ollum re-appears before you, rubbing its hands...*"Excellent, precious, excellent!  It found the first piece of the Crolna!  Shiny piece, yesss!"*"Most useful it will be, trust us.  Seek out the rest of it, gollum, the rest, the rest..."*Just as suddenly, the vision fades.*`,
    ollum_reform: `Again, Ollum appears before your eyes...*"Ah, we sees it has begun to put the Crolna back together!  Excellent, precious!"*"Now it's on to the heart of the mystery, yesss.  Once it's whole, the Crolna can cure the land, gollum."*"Of course it'll need the courage to wield it, but we has faith in it, precious, and its judgment.  Mostly."*"Beware its enemy, though, sss, for they'll catch it with lies hidden in half truths.  Tricksy.  Not like us."*Ollum fades away...*`,
    ollum_destiny: `Ollum appears in a vision again...*"It has done well, and we is proud of it, so proud, precious.  Now is the time for it to complete its destiny, gollum."*"It knows what it needs to do - it doesn't fail us!  It doesn't!  Or else, sss."*Ollum fades away...*`,
    ollum_welcome: `The vision of Ollum appears before you...*"Welcome to the wide world of Cythera, precious!  A ready hero`,
    ollum_unseen: `"Oh, by the way, don't it worry, none of its fellow adventurers can see us, gollum."*"They doesn't even notice what's going on - they isn't quick enough to catch this instant.  Slow, stupid, fat."*`,
    ollum_alone: `"Adventuring alone can be hazardous, precious - perhaps it should have taken somebody from Land King Hall.  Somebody juicy."*`,
    ollum_hecky: `"Perhaps that eager little Hecky might want to come along.  Might be worth asking, if his daddy lets him grow up, sss."*`,
    ollum_two_things_opening: `"Perhaps some eager young warrior living in Land King Hall might want to come along, if his daddy lets him grow up, gollum."*`,
    ollum_two_things: `"There's basically two important things it needs to look into right away, precious - a plague in Catamarca, and a kidnapping in Odemia."*"Either way, it follows the road down along the coast - Odemia is the first city it finds, Catamarca the second, yesss."*"Good luck - and to start out, it only travels in the daytime, since nasty things come out at night.  Nassstier than us."*"And whatever it does, it stays away from the shoreline!  Wet.  Nasty.  Fisssh."*`,
    ollum_cademia: `The vision of Ollum returns before you...*"Cademia.  Mother City, precious.  Once it's lived in Cademia, no other place can be home, gollum."*"It keeps its wits here - miscreants roam the back alleys, especially at night, sss, nasty ones"*"Much lies buried beneath its ancient buildings, yesss, deep and dark - the city has history that's lost now.  We remembers.  We remembers everything."*Ollum fades away...*`,
    ollum_danger: `The vision of Ollum returns before you, wringing its hands...*"Danger!  It's in great danger, precious!  Great danger!"*"Beware what lies buried here, gollum - some things is best left undisturbed, yesss, left in the dark!"*"It must choose its own path, but what's here would destroy the whole world if it got loose!"*"And not even Rick with all his powers could stop this abomination, sss!"*"It'll tell it anything to get it to do its bidding - it mustn't even stoop to talk to it!  Nasty liar!  Not like us, precious, we is honest, we is."*"We begs it, we begs, leave well enough alone..."Ollum fades away...*`,
    ollum_abydos: `The vision of Ollum returns before you...*"Lost Abydos, gollum - now just a reminder of a great failure, precious..."*"None of the Mages dares admit it, but Abydos was destroyed by their leader, yesss, their own leader."*"The Mage Tavara destroyed the city when the people rejected his leadership.  Sss.  We doesn't talk about the master.  We didn't say that."*"If it goes in the tunnels below the city, it'll even find his workroom - but careful, precious, careful."*"That place is guarded by a fearsome magical being that it'd call a daemon.  Big.  Hungry.  Not friends with us."*"Don't say it wasn't warned, gollum."Ollum fades away...*`,
    ollum_four_parts: `The vision of Ollum returns before you...*"It's doing well, precious - putting the Crolna back together is most important, yesss, most important of all."*"But there's more parts to find - four, gollum, four shiny parts.  We counted."*"Getting the first two was the easy part - the next two will be a true test of what it's made of, sss."*Ollum fades away...*`,
    scroll_1: `WELCOME, PUNY HUMAN, TO MY DIABOLICAL TEST!  MWAHAHAHA!  It is not hard to pass - for the merest worm could pass it, and a worm is all you are to ME - yet it shall grant you the pitiful skills you need to survive my later, far crueller schemes (you may feel like a creature in a cage; GOOD; you ARE one).  I trust my loathsome creature Ollum did not startle you.  His appearance is hideous, for I made him so, with these very hands, on a Tuesday. \n\nYou have already passed the first part of my test - you have read this note!  FOOL!  You have played directly into my hands!  Next, you must pull that nearby lever to open the gate, leading you to the next room of my labyrinth of DOOM.  There you will find a locked trapdoor.  Find the key, open it, and then go down the ladder, ever downward, into the darkness I have so lovingly prepared.`,
    scroll_2: `AH-HA!  The key is NOT in this chest!  DECEIVED!  Do you feel the sting of my cunning, little insect?  I laughed for an hour when I wrote this.  Look to your south - notice anything interesting about the wall, or is your feeble mind already crumbling before my genius?  Try using it...\n\nOh, you might want to use one of the torches in this chest, for it will provide some light for you if you wield it in your hands... yes, I am generous, in my way.  A benevolent tyrant of the dark.  Do not thank me.  It would only make it worse.`,
    scroll_3: `Ah, very good - very observant, finding that second secret door!  I underestimated you, worm... NO.  I never underestimate.  I merely allow you the ILLUSION of triumph, the better to crush it later.  Not all discoveries like this lead to reward, unfortunately for you - some lead to spikes, some to pits, some to a small room where I keep the screaming.  However, this one does lead to reward... FOR NOW.  MWAHAHA.`,
    scroll_4: `THIS room is trickier, my wriggling captive - the door is locked by a spell of MY OWN DEVISING, which took me the better part of an afternoon and is quite the most elegant thing ever wrought by a mind so vast as mine.  You have but ONE chance to get this door open - take that strange-looking object, what your primitive tongue would call a bomb.  Pick it up, use it to light it, and then toss it so it lands right next to the door.  Stand back and let time pass... and while you wait, reflect on how utterly you are in my power.  I certainly shall.`,
    scroll_5: `Not all levers are easily found, and THIS one I have hidden with a malice so refined it borders on art - perhaps if you re-arranged things a bit here... (don't worry - all the crates are empty, for I emptied them myself, cackling, so it is easy for you to move them, and you need not waste your time searching them; your time belongs to ME now, and I shall spend it as I please!  MWAHAHAHAHA!)`,
  },
};

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const [htmlPath = 'index.html', dataPath, outDir] = process.argv.slice(2);
  if (!dataPath || !outDir) { console.error('usage: voices_patch.mjs index.html <Cythera Data.data> <out dir>'); process.exit(2); }
  process.exit(buildCast(CAST, { htmlPath, dataPath, outDir }) ? 0 : 1);
}
